<?php
namespace Tourfic\Admin;

defined( 'ABSPATH' ) || exit;

trait TF_API_Documentation_Examples {
	private function get_general_settings_example_response() {
		return wp_json_encode( $this->get_general_settings_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_general_settings_example_payload() {
		return array(
			'general-notice-heading'           => '',
			'general-option-notice-one'       => '',
			'disable-services'                => '',
			'tf-date-format-for-users'        => 'Y/m/d',
			'tf-week-day-flatpickr'           => '0',
			'tf-quick-checkout'               => '',
			'template_heading'                => '',
			'tf-template'                     => array(
				'single-hotel'                  => 'design-2',
				'single-hotel-layout'           => array(
					array(
						'label'  => 'Description',
						'slug'   => 'description',
						'status' => '1',
					),
				),
				'single-hotel-layout-part-1'    => array(
					array(
						'label'  => 'Description',
						'slug'   => 'description',
						'status' => '1',
					),
				),
				'single-hotel-layout-part-2'    => array(
					array(
						'label'  => 'Facilities',
						'slug'   => 'facilities',
						'status' => '1',
					),
				),
				'hotel-archive'                 => 'design-2',
				'hotel_archive_design_2_bannar' => 'https://example.com/uploads/hotel-archive-2.jpg',
				'hotel_archive_design_3_bannar' => 'https://example.com/uploads/hotel-archive-3.jpg',
				'hotel_archive_view'            => 'list',
				'single-tour'                   => 'design-1',
				'single-tour-layout'            => array(
					array(
						'label'  => 'Gallery',
						'slug'   => 'gallery',
						'status' => '1',
					),
				),
				'single-tour-layout-part-1'     => array(
					array(
						'label'  => 'Description',
						'slug'   => 'description',
						'status' => '1',
					),
				),
				'single-tour-layout-part-2'     => array(
					array(
						'label'  => 'FAQ',
						'slug'   => 'faq',
						'status' => '1',
					),
				),
				'tour-archive'                  => 'design-2',
				'tour_archive_design_2_bannar'  => 'https://example.com/uploads/tour-archive-2.jpg',
				'tour_archive_design_3_bannar'  => 'https://example.com/uploads/tour-archive-3.jpg',
				'tour_archive_view'             => 'list',
				'single-apartment'              => 'default',
				'single-aprtment-layout-part-1' => array(
					array(
						'label'  => 'Description',
						'slug'   => 'description',
						'status' => '1',
					),
				),
				'single-aprtment-layout-part-2' => array(
					array(
						'label'  => 'Review',
						'slug'   => 'review',
						'status' => '1',
					),
				),
				'apartment-archive'             => 'design-1',
				'apartment_archive_design_1_bannar' => 'https://example.com/uploads/apartment-archive-1.jpg',
				'apartment_archive_design_2_bannar' => 'https://example.com/uploads/apartment-archive-2.jpg',
				'apartment_archive_view'        => 'list',
				'single-car'                    => 'design-1',
				'single-car-layout'             => array(
					array(
						'label'  => 'Description',
						'slug'   => 'description',
						'status' => '1',
					),
				),
				'car-archive'                   => 'design-1',
				'car_archive_design_1_bannar'   => 'https://example.com/uploads/car-archive-1.jpg',
				'car_archive_view'              => 'grid',
				'car_archive_driver_min_age'    => '',
				'car_archive_driver_max_age'    => '',
			),
			'container_heading'               => '',
			'tf-container'                    => 'boxed',
			'tf-container-width'              => '1280',
			'signle_tour_heading'             => '',
			'tour-option-notice-one'          => '',
			't-review'                        => '',
			't-share'                         => '',
			't-related'                       => '',
			'rt-title'                        => 'You might also like',
			'rt-description'                  => 'Related tours section description.',
			'rt_display'                      => 'auto',
			'tf-related-tours'                => '',
			't-enquiry-email'                 => '',
			't-auto-draft'                    => '',
			't-show-expire-tour'              => '',
			't-hide-start-price'              => '',
			'tour_archive_price_minimum_settings' => 'all',
			'tour_booking_form_button_text'   => '',
			'tour-option-notice-two'          => '',
			'deposit-title'                   => '',
			'deposit-subtitle'                => 'Partial payment information.',
			'notice_shortcode'                => '',
			'itinerary-builder-setings'       => array(
				'itinerary-field'              => array(
					'1' => array(
						'sleep-mode-title' => '4 days',
						'sleep-mode-icon'  => 'ri-time-line',
					),
				),
				'elevtion_type'                => 'Meter',
				'itinerary-downloader'         => '1',
				'itinerary-downloader-title'   => 'Want to read it later?',
				'itinerary-downloader-desc'    => 'Download this tour PDF brochure.',
				'itinerary-downloader-button'  => 'Download Now',
				'tour_thumbnail_height'        => '',
				'tour_thumbnail_width'         => '',
				'company_logo'                 => '',
				'company_desc'                 => '',
				'company_email'                => '',
				'company_address'              => '',
				'company_phone'                => '',
				'expert_label'                 => '',
				'expert_name'                  => '',
				'expert_email'                 => '',
				'expert_phone'                 => '',
				'expert_logo'                  => '',
			),
			'itinerary_map'                  => '',
			'travel_mode'                    => 'DRIVING',
			'confirmation_fields_heading'    => '',
			'tour-option-notice-four'        => '',
			'book-confirm-field'             => 'serialized string',
			'booking-confirmation-msg'       => 'Booked Successfully',
			'booking_tour_heading'           => '',
			'disable_traveller_info'         => '',
			'custom_fields_heading'          => '',
			'without-payment-field'          => 'serialized string',
			'tour_popup_extras_text'         => 'Popup text for tour extras.',
			'tour_traveler_details_text'     => 'Traveler details privacy notice.',
			'label_off_heading'              => '',
			'hotel-option-notice-one'        => '',
			'h-review'                       => '',
			'h-share'                        => '',
			'feature-filter'                 => '1',
			'h-enquiry-email'                => '',
			'hotel_archive_price_minimum_settings' => 'all',
			'hotel_facilities_cats'          => 'serialized string',
			'hotel_booking_form_button_text' => '',
			'hotel_booking_check_button_text' => '',
			'hotel_room_heading'             => '',
			'hotel-option-notice-two'        => '',
			'enable_child_age_limit'         => '',
			'children_age_limit'             => '',
			'hotel_popup_heading'            => '',
			'hotel-option-notice-three'      => '',
			'hotel_service_popup_title'      => 'Add Service to your Booking.',
			'hotel_service_popup_subtile'    => 'Select the services you want to add to your booking.',
			'hotel_service_popup_action'     => 'Continue to booking',
			'hotel_confirmation_fields_heading' => '',
			'hotel-book-confirm-field'       => 'serialized string',
			'hotel-booking-confirmation-msg' => 'Booked Successfully',
			'booking_hotel_heading'          => '',
			'enable_guest_info'              => '1',
			'hotel_custom_fields_heading'    => '',
			'hotel_guest_info_fields'        => 'serialized string',
			'hotel_guest_details_text'       => 'Guest details privacy notice.',
			'apartment-option-notice'        => '',
			'amenities_cats'                 => array(
				'1' => array(
					'amenities_cat_name' => 'Business Facilities',
					'amenities_cat_icon' => '',
				),
			),
			'disable-apartment-review'       => '',
			'disable-apartment-share'        => '',
			'disable-related-apartment'      => '',
			'apartment_booking_form_button_text' => '',
			'disable-car-share'              => '',
			'car_booking_form_button_text'   => 'Reserve',
			'car-book-confirm-field'         => 'serialized string',
			'car-booking-confirmation-msg'   => '',
			'disable-car-time-slots'         => '',
			'car_time_interval'              => '30',
			'front-dash-heading'             => '',
			'front-dash-notice'              => '',
			'fd_logo'                        => '',
			'fd_logo_minified'               => '',
			'fd_logo_mobile'                 => '',
			'tf_user_permission'             => array(
				'vendor_post_permission'     => array( 'hotel', 'tour', 'apartment', 'car_rental' ),
				'vendor_tax_permission'      => array( 'hotel_location' ),
				'vendor_can_manage'          => array( 'view_hotel_enquiry' ),
				'manager_post_permission'    => array( 'hotel', 'tour', 'apartment', 'car_rental' ),
				'manager_tax_permission'     => array( 'hotel_location' ),
				'manager_can_manage'         => array( 'view_hotels' ),
			),
			'notice'                         => '',
			'search-option-heading'          => '',
			'search-option-notice'           => '',
			'search-result-page'             => 8,
			'posts_per_page'                 => '10',
			'hotel_search_heading'           => '',
			'date_hotel_search'              => '',
			'disable_hotel_child_search'     => '',
			'required_location_hotel_search' => '1',
			'hide_hotel_location_search'     => '',
			'tour_search_heading'            => '',
			'date_tour_search'               => '',
			'disable_child_search'           => '',
			'disable_infant_search'          => '',
			'required_location_tour_search'  => '1',
			'hide_tour_location_search'      => '',
			'apartment_search_heading'       => '',
			'date_apartment_search'          => '',
			'disable_apartment_child_search' => '',
			'disable_apartment_infant_search' => '',
			'car_search_heading'             => '',
			'pick_drop_car_search'           => '1',
			'pick_drop_date_car_search'      => '',
			'log_reg_settings'               => array(
				'login_page'            => '659',
				'login_redirect_type'   => 'page',
				'login_redirect_page'   => '662',
				'login_redirect_url'    => 'https://example.com/tf-dashboard',
				'register_page'         => '660',
				'register_redirect_type'=> 'page',
				'register_redirect_page'=> '659',
				'register_redirect_url' => 'https://example.com/tf-login',
			),
			'map_settings_heading'           => '',
			'mapsettings-official-docs'      => '',
			'google-page-option'             => 'googlemap',
			'tf-googlemapapi'                => 'YOUR_GOOGLE_MAPS_API_KEY',
			'map_template_marker'            => '',
			'map_marker_width'               => '35',
			'map_marker_height'              => '45',
			'wishlist_heading'               => '',
			'wishlistsettings-official-docs' => '',
			'wl-for'                         => array( 'li', 'lo' ),
			'wl-bt-for'                      => array( '1', '2', '3' ),
			'wl-page'                        => '24',
			'review_heading'                 => '',
			'review-settings-official-docs'  => '',
			'r-for'                          => array( 'li' ),
			'r-auto-publish'                 => '',
			'r-base'                         => '5',
			'r-hotel'                        => 'serialized string',
			'r-tour'                         => 'serialized string',
			'r-apartment'                    => 'serialized string',
			'r-car'                          => 'serialized string',
			'tf_delete_old_review_fields_button' => '',
			'tf_delete_old_complete_review_button' => '',
			'optimization_heading'           => '',
			'optimize-settings-official-docs' => '',
			'css_min'                        => '1',
			'js_min'                         => '1',
			'cdn_heading'                    => '',
			'ftpr_cdn'                       => '',
			'fnybx_cdn'                      => '',
			'slick_cdn'                      => '',
			'fa_cdn'                         => '',
			'select2_cdn'                    => '',
			'remix_cdn'                      => '',
			'leaflet_cdn'                    => '',
			'swal_cdn'                       => '',
			'chart_cdn'                      => '',
			'permalink_heading'              => '',
			'permalink_notice'               => '',
			'tour-permalink-setting'         => 'tours',
			'hotel-permalink-setting'        => 'hotels',
			'apartment-permalink-setting'    => 'apartments',
			'car-permalink-setting'          => 'cars',
			'affiliate_heading'              => '',
			'tf-affiliate'                   => '',
			'email_template_settings'        => array(
				'enable_admin_conf_email'             => '1',
				'admin_confirmation_email_template'   => 89,
				'enable_admin_canc_email'             => '1',
				'admin_cancellation_email_template'   => 95,
				'enable_offline_admin_conf_email'     => '1',
				'admin_offline_confirmation_email_template' => 93,
				'enable_vendor_conf_email'            => '1',
				'vendor_confirmation_email_template'  => 90,
				'enable_vendor_canc_email'            => '1',
				'vendor_cancellation_email_template'  => 96,
				'enable_offline_vendor_conf_email'    => '1',
				'vendor_offline_confirmation_email_template' => 94,
				'enable_customer_conf_email'          => '1',
				'customer_confirmation_email_template' => 91,
				'enable_customer_canc_email'          => '1',
				'customer_cancellation_email_template' => 97,
				'enable_offline_customer_conf_email'  => '1',
				'customer_offline_confirmation_email_template' => 92,
			),
			'qr-code-title'                  => '',
			'qrcode-official-docs'           => '',
			'qr_logo'                        => '',
			'qr_background'                  => '',
			'qr-ticket-title'                => '',
			'qr-ticket-prefix'               => '',
			'qr-ticket-content'              => '',
			'qr-ticket-verify'               => '1',
			'integration_heading'            => '',
			'tf-integration'                 => array(
				'hotel-integrate-pabbly-webhook' => '',
				'h-enquiry-pabbly-webhook'      => '',
				'tour-integrate-pabbly-webhook' => '',
				't-enquiry-pabbly-webhook'      => '',
				'apartment-integrate-pabbly-webhook' => '',
				'a-enquiry-pabbly-webhook'      => '',
				'car-integrate-pabbly-webhook'  => '',
				'tf-new-order-pabbly-webhook'   => '',
				'tf-new-customer-pabbly-webhook' => '',
				'hotel-integrate-zapier-webhook' => '',
				'h-enquiry-zapier-webhook'      => '',
				'tour-integrate-zapier-webhook' => '',
				't-enquiry-zapier-webhook'      => '',
				'apartment-integrate-zapier-webhook' => '',
				'a-enquiry-zapier-webhook'      => '',
				'car-integrate-zapier-webhook'  => '',
				'tf-new-order-zapier-webhook'   => '',
				'tf-new-customer-zapier-webhook' => '',
				'tf-google-calendar-client_id'  => '',
				'tf-google-calendar-secret_key' => '',
				'tf-google-calendar-redirect_url' => 'https://example.com/wp-json/tourfic/v1/integration/google-api',
			),
			'cancellation-official-docs'     => '',
			'timezone-title'                 => '',
			'cancellation_time_zone'         => 'Pacific/Midway',
			'hotel-title'                    => '',
			'cancellation_hotel_checkin_time' => '',
			'tour-title'                     => '',
			'cancellation_tour_checkin_time' => '',
			'apartment-title'                => '',
			'cancellation_apartment_checkin_time' => '',
			'export-import-notice-one'       => '',
			'backup'                         => '',
		);
	}

	private function get_hotel_room_availability_example_response() {
		return wp_json_encode( $this->get_hotel_room_availability_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_hotel_room_availability_update_example_response() {
		return wp_json_encode( $this->get_hotel_room_availability_update_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_hotel_room_availability_update_example_payload() {
		return array(
			'status'            => true,
			'message'           => 'Availability updated successfully.',
			'avail_date'        => array(
				array(
					'check_in'    => '2026/05/01',
					'check_out'   => '2026/05/01',
					'price_by'    => '1',
					'price'       => '200',
					'adult_price' => '',
					'child_price' => '',
					'status'      => '',
					'editable'    => false,
					'start'       => '2026-05-01',
					'title'       => 'Price: <span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>200.00</bdi></span>',
				),
				array(
					'check_in'    => '2026/05/02',
					'check_out'   => '2026/05/02',
					'price_by'    => '1',
					'price'       => '20',
					'adult_price' => '',
					'child_price' => '',
					'status'      => 'available',
					'editable'    => false,
					'start'       => '2026-05-02',
					'title'       => 'Price: <span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>20.00</bdi></span>',
				),
			),
			'avail_date_encoded' => '{"2026\\/05\\/01":{"check_in":"2026\\/05\\/01","check_out":"2026\\/05\\/01","price_by":"1","price":"200","adult_price":"","child_price":"","status":""},"2026\\/05\\/02":{"check_in":"2026\\/05\\/02","check_out":"2026\\/05\\/02","price_by":"1","price":"20","adult_price":"","child_price":"","status":"available"}}',
		);
	}

	private function get_hotel_room_availability_example_payload() {
		return array(
			array(
				'check_in'    => '2026/05/01',
				'check_out'   => '2026/05/01',
				'price_by'    => '1',
				'price'       => '20',
				'adult_price' => '',
				'child_price' => '',
				'status'      => 'available',
				'editable'    => false,
				'start'       => '2026-05-01',
				'title'       => 'Price: <span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>20.00</bdi></span>',
			),
			array(
				'check_in'    => '2026/05/02',
				'check_out'   => '2026/05/02',
				'price_by'    => '1',
				'price'       => '20',
				'adult_price' => '',
				'child_price' => '',
				'status'      => 'available',
				'editable'    => false,
				'start'       => '2026-05-02',
				'title'       => 'Price: <span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>20.00</bdi></span>',
			),
		);
	}

	private function get_room_opt_example_payload() {
		return array(
			'unique_id'                 => '1703067301412',
			'order_id'                  => '',
			'enable'                    => '1',
			'tf_single_rom_layout_opt'  => 'global',
			'tf_single_room_template'   => 'design-1',
			'num-room'                  => '',
			'reduce_num_room'           => '0',
			'gallery'                   => '',
			'bed'                       => '',
			'adult'                     => '',
			'child'                     => '',
			'children_age_limit'        => '',
			'footage'                   => '',
			'features'                  => array(),
			'house_rules_title'         => '',
			'house_rules'               => array(),
			'minimum_stay_requirement'  => '',
			'maximum_stay_requirement'  => '',
			'pricing-by'                => '1',
			'price'                     => '',
			'adult_price'               => '',
			'child_price'               => '',
			'room-options'              => array(),
			'discount_hotel_type'       => 'none',
			'discount_hotel_price'      => '',
			'price_multi_day'           => '',
			'allow_deposit'             => '0',
			'deposit_type'              => 'none',
			'deposit_amount'            => '',
			'cancelation-section-title' => '',
			'calcellation_policy'       => array(),
			'ical_url'                  => '',
			'avil_by_date'              => '0',
			'avail_date'                => '',
			'booking-by'                => '1',
			'booking-url'               => '',
			'booking-attribute'         => '0',
			'booking-query'             => '',
		);
	}

	private function get_add_room_example_request() {
		$body = wp_json_encode(
			array(
				'title'       => 'Deluxe Room',
				'content'     => 'Sea view room description.',
				'tf_room_opt' => $this->get_room_opt_example_payload(),
			),
			JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
		);
		return "POST /wp-json/tf/v1/add-room\nX-API-Key: your-api-key\nContent-Type: application/json\n\n" . $body;
	}

	private function get_update_room_example_request() {
		$body = wp_json_encode(
			array(
				'id'          => 654,
				'title'       => 'Deluxe Room Updated',
				'content'     => 'Updated room description.',
				'tf_room_opt' => $this->get_room_opt_example_payload(),
			),
			JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
		);
		return "POST /wp-json/tf/v1/update-room\nX-API-Key: your-api-key\nContent-Type: application/json\n\n" . $body;
	}

	private function get_hotels_example_response() {
		return wp_json_encode( $this->get_hotels_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_tours_example_response() {
		return wp_json_encode( $this->get_tours_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_tours_example_payload() {
		return array(
			'tours' => array(
				array(
					'id'               => 56,
					'permalink'        => 'https://example.com/tours/sample-city-tour/',
					'title'            => 'Sample City Tour',
					'content'          => 'Tour description content.',
					'status'           => 'publish',
					'author'           => 'admin',
					'tour_destination' => 'Greece, Turkey',
					'tour_attraction'  => 'Sample Attraction',
					'tour_activities'  => 'Sky Diving',
					'tour_features'    => '',
					'tour_type'        => '',
					'date'             => 'January 15, 2024',
					'featured_image'   => 'https://example.com/uploads/tour-featured.jpg',
					'tf_tours_opt'     => array(
						'id'                          => '898',
						'post_title'                  => 'sample-city-tour',
						'slug'                        => 'sample-city-tour',
						'post_content'                => 'Tour description content.',
						'thumbnail'                   => 'https://example.com/uploads/tour-thumb.jpg',
						'adult_price'                 => '90',
						'child_price'                 => '80',
						'infant_price'                => '40',
						'tour_as_featured'            => '',
						'tf_single_tour_layout_opt'   => 'single',
						'tf_single_tour_template'     => 'design-2',
						'tour_types'                  => array( null ),
						'refund_des'                  => 'Ask for Refund',
						'highlights-section-title'    => 'Highlights',
						'contact-info-section-title'  => 'Contact Information',
						'tour-traveller-info'         => '',
						'booking-by'                  => '1',
						'booking-url'                 => '',
						'booking-attribute'           => '',
						'booking-query'               => '',
						'itinerary-section-title'     => 'Travel Itinerary',
						'faq-section-title'           => 'Frequently Asked Questions',
						't-enquiry-section'           => '1',
						't-enquiry-option-icon'       => 'fa-solid fa-question',
						't-enquiry-option-title'      => 'Have a question in mind',
						't-enquiry-option-content'    => 'Looking for more info? Send a question to the tour agent to find out more.',
						't-enquiry-option-btn'        => 'Ask a Question',
						'tc-section-title'            => 'Tour Terms & Conditions',
						'booking-section-title'       => 'Book This Tour',
						'description-section-title'   => 'Description',
						'map-section-title'           => 'Maps',
						'review-section-title'        => 'Average Guest Reviews',
						't-wishlist'                  => '',
						'type'                        => 'continuous',
						'pricing'                     => 'person',
						'discount_type'               => 'none',
						'discount_price'              => '',
						'disable_adult_price'         => '',
						'disable_child_price'         => '',
						'disable_infant_price'        => '',
						'allow_deposit'               => 'off',
						'deposit_type'                => '',
						'deposit_amount'              => '',
						'text_location'               => '',
						'location'                    => array(
							'address'   => 'Example City, Country',
							'latitude'  => '37.9755648',
							'longitude' => '23.7348324',
							'zoom'      => '8',
						),
						'group_price'                 => '',
						'allowed_time'                => '',
						'min_days_before_book'        => '',
						'disable_same_day'            => '',
						'disable_range'               => '',
						'disabled_day'                => '',
						'disable_specific'            => '',
						'cont_min_people'             => '1',
						'cont_max_people'             => '5',
						'custom_avail'                => '',
						'custom_pricing_by'           => '',
						'cont_custom_date'            => '',
						'fixed_availability'          => array(
							'min_seat' => '',
							'max_seat' => '',
							'date'     => array(
								'from' => '',
								'to'   => '',
							),
						),
						'max_capacity'                => '',
						'itinerary-downloader'        => '',
						'itinerary-downloader-title'  => '',
						'itinerary-downloader-desc'   => '',
						'itinerary-downloader-button' => '',
						'tour_thumbnail_height'       => '',
						'tour_thumbnail_width'        => '',
						'company_logo'                => '',
						'company_desc'                => '',
						'company_email'               => '',
						'company_address'             => '',
						'company_phone'               => '',
						'itinerary-expert'            => '',
						'expert_label'                => '',
						'expert_name'                 => '',
						'expert_email'                => '',
						'expert_phone'                => '',
						'expert_logo'                 => '',
						'itinerary-expert-viber'      => '',
						'itinerary-expert-whatsapp'   => '',
						't-review'                    => '',
						't-share'                     => '',
						't-related'                   => '',
						'tour-traveler-info'          => '',
						'cont_max_capacity'           => '',
						'tour_destination'            => 'Greece, Turkey',
						'features'                    => array( null ),
						'tour_activities'             => 'Sky Diving',
						'tour_attraction'             => 'Sample Attraction',
						'tour_gallery'                => '50,51,53',
						'tour_video'                  => 'https://youtu.be/sample',
						'additional_information'      => 'Additional tour information.',
						'hightlights_thumbnail'       => 'https://example.com/uploads/highlight.jpg',
						'duration'                    => '3',
						'duration_time'               => 'Day',
						'night'                       => '1',
						'night_count'                 => '4',
						'group_size'                  => '14',
						'language'                    => 'English',
						'email'                       => 'contact@example.com',
						'phone'                       => '+1 (000) 000-0000',
						'fax'                         => '',
						'website'                     => 'https://example.com',
						'tour-extra'                  => '',
						'faqs'                        => '',
						'inc'                         => array(
							array( 'inc' => 'Specialized bilingual guide' ),
							array( 'inc' => 'Entrance fees' ),
						),
						'exc'                         => array(
							array( 'exc' => 'Travel insurance' ),
							array( 'exc' => 'Personal expenses' ),
						),
						'inc_icon'                    => 'fa fa-check',
						'exc_icon'                    => 'fa fa-times',
						'inc_exc_bg'                  => '',
						'itinerary'                   => '',
						'itinerary_gallery'           => '',
						'terms_conditions'            => 'Tour terms and conditions content.',
						'post_date'                   => '2024-01-15 10:20:57',
					),
					'reviews'          => array(
						'tour_reviews' => 0,
						'review_text'  => '',
					),
					'start_price'      => '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>90.00</bdi></span>',
				),
			),
			'total' => 6,
		);
	}

	private function get_hotels_example_payload() {
		return array(
			'hotels' => array(
				array(
					'id'             => 52,
					'permalink'      => 'https://example.com/hotels/boutique-city-hotel-gallo/',
					'title'          => 'Boutique City Hotel Gallo',
					'content'        => 'Hotel description content.',
					'status'         => 'publish',
					'author'         => 'admin',
					'hotel_location' => 'Switzerland',
					'hotel_feature'  => 'Bathtub, Breakfast, Swimming Pool, Wifi',
					'hotel_type'     => 'Luxury, Boutique',
					'date'           => 'January 15, 2024',
					'featured_image' => 'https://example.com/uploads/hotel-featured.jpg',
					'tf_hotels_opt'  => array(
						'id'                              => '1099',
						'post_title'                      => 'boutique-city-hotel-gallo',
						'slug'                            => 'boutique-city-hotel-gallo',
						'content'                         => 'Hotel description content.',
						'address'                         => '',
						'[map][address]'                  => 'Example Street, Example City, Country',
						'map'                             => array(
							'address'   => 'Example Street, Example City, Country',
							'latitude'  => '25.701643',
							'longitude' => '32.6422566',
							'zoom'      => '5',
						),
						'[map][latitude]'                 => '25.701643',
						'[map][longitude]'                => '32.6422566',
						'[map][zoom]'                     => '5',
						'gallery'                         => '43,44,45',
						'video'                           => 'https://www.youtube.com/watch?v=example',
						'featured'                        => '',
						'featured_text'                   => 'Hot Deal',
						'tf_single_hotel_layout_opt'      => 'single',
						'tf_single_hotel_template'        => 'design-2',
						'room-section-title'              => 'Available Rooms',
						'room'                            => array(
							array(
								'enable'                   => '1',
								'title'                    => 'VIP Premium Deluxe Twin Room 2 Beds',
								'unique_id'                => '1703066080098',
								'room_preview_img'         => 'https://example.com/uploads/room-preview-1.jpg',
								'num-room'                 => '10',
								'reduce_num_room'          => '1',
								'bed'                      => '2',
								'adult'                    => '2',
								'child'                    => '1',
								'children_age_limit'       => '',
								'footage'                  => '250 sqr',
								'description'              => 'Room description.',
								'minimum_stay_requirement' => '1',
								'maximum_stay_requirement' => '10',
								'pricing-by'               => '1',
								'booking-by'               => '',
								'booking-url'              => '',
								'booking-attribute'        => 0,
								'booking-query'            => '',
								'price'                    => '88',
								'adult_price'              => '',
								'child_price'              => '',
								'discount_hotel_type'      => 'percent',
								'discount_hotel_price'     => '10',
								'price_multi_day'          => '1',
								'allow_deposit'            => '',
								'deposit_type'             => '',
								'deposit_amount'           => '',
								'avil_by_date'             => '',
								'gallery'                  => '46,47,48',
								'features'                 => array(
									'0' => 24,
									'1' => 28,
								),
								'avail_date'               => '0',
							),
						),
						'room_gallery'                    => '{"1":"https://example.com/uploads/room-gallery-1.jpg,https://example.com/uploads/room-gallery-2.jpg"}',
						'features'                        => '[["Bathtub","Breakfast","Swimming Pool","Wifi"]]',
						'avail_date'                      => '0|0',
						'hotel_feature'                   => 'Bathtub, Breakfast, Swimming Pool, Wifi',
						'features_icon'                   => 'Bathtub(ri-css3-line), Breakfast(ri-goblet-line), Swimming Pool(fab fa-audible), Wifi(ri-base-station-line)',
						'hotel_location'                  => 'Switzerland',
						'hotel_type'                      => 'Luxury, Boutique',
						'airport_service'                 => '0',
						'airport_service_type'            => '',
						'[airport_pickup_price][airport_pickup_price_type]' => '',
						'airport_pickup_price'            => array(
							'airport_pickup_price_type'    => '',
							'airport_service_fee_adult'    => '',
							'airport_service_fee_children' => '',
							'airport_service_fee_fixed'    => '',
						),
						'[airport_pickup_price][airport_service_fee_adult]'    => '',
						'[airport_pickup_price][airport_service_fee_children]' => '',
						'[airport_pickup_price][airport_service_fee_fixed]'    => '',
						'[airport_dropoff_price][airport_pickup_price_type]'   => '',
						'airport_dropoff_price'           => array(
							'airport_pickup_price_type'    => '',
							'airport_service_fee_adult'    => '',
							'airport_service_fee_children' => '',
							'airport_service_fee_fixed'    => '',
						),
						'[airport_dropoff_price][airport_service_fee_adult]'    => '',
						'[airport_dropoff_price][airport_service_fee_children]' => '',
						'[airport_dropoff_price][airport_service_fee_fixed]'    => '',
						'[airport_pickup_dropoff_price][airport_pickup_price_type]' => '',
						'airport_pickup_dropoff_price'   => array(
							'airport_pickup_price_type'    => '',
							'airport_service_fee_adult'    => '',
							'airport_service_fee_children' => '',
							'airport_service_fee_fixed'    => '',
						),
						'[airport_pickup_dropoff_price][airport_service_fee_adult]'    => '',
						'[airport_pickup_dropoff_price][airport_service_fee_children]' => '',
						'[airport_pickup_dropoff_price][airport_service_fee_fixed]'    => '',
						'faq-section-title'               => 'Faq’s',
						'faq'                             => 'serialized string',
						'h-enquiry-section'               => '1',
						'h-enquiry-option-icon'           => 'fa fa-question-circle-o',
						'h-enquiry-option-title'          => 'Have a question in mind',
						'h-enquiry-option-content'        => 'Looking for more info? Send a question to the property to find out more.',
						'h-enquiry-option-btn'            => 'Ask a Question',
						'h-review'                        => '',
						'h-share'                         => '',
						'h-wishlist'                      => '',
						'popular-section-title'           => 'Popular Features',
						'review-section-title'            => 'Average Guest Reviews',
						'tc-section-title'                => 'Hotel Terms & Conditions',
						'tc'                              => 'Terms and conditions content.',
						'post_date'                       => '2024-01-15 08:13:23',
						'tf_rooms'                        => array( 69, 71 ),
					),
					'reviews'        => array(
						'hotel_reviews' => 0,
						'review_text'   => '',
					),
					'start_price'    => '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>59.00</bdi></span>',
					'rooms'          => array(
						array(
							'ID'                    => 71,
							'post_author'           => '1',
							'post_date'             => '2026-04-27 03:54:55',
							'post_date_gmt'         => '2026-04-27 03:54:55',
							'post_content'          => 'Room post content.',
							'post_title'            => 'Premium Deluxe Twin',
							'post_excerpt'          => '',
							'post_status'           => 'publish',
							'comment_status'        => 'closed',
							'ping_status'           => 'closed',
							'post_password'         => '',
							'post_name'             => 'premium-deluxe-twin',
							'to_ping'               => '',
							'pinged'                => '',
							'post_modified'         => '2026-04-27 03:54:55',
							'post_modified_gmt'     => '2026-04-27 03:54:55',
							'post_content_filtered' => '',
							'post_parent'           => 0,
							'guid'                  => 'https://example.com/rooms/premium-deluxe-twin/',
							'menu_order'            => 0,
							'post_type'             => 'tf_room',
							'post_mime_type'        => '',
							'comment_count'         => '0',
							'filter'                => 'raw',
						),
					),
				),
			),
			'total' => 6,
		);
	}

	private function get_tour_opt_example_payload() {
		return array(
			'tour_as_featured'                => '0',
			'featured_text'                   => 'Hot Deal',
			'is_taxable'                      => '0',
			'taxable_class'                   => 'standard',
			'tf_single_tour_layout_opt'       => 'global',
			'tf_single_tour_template'         => 'design-1',
			'tour_gallery'                    => '50,51,53',
			'tour_video'                      => 'https://youtu.be/sample',
			'location'                        => array(
				'address'   => 'Example City, Country',
				'latitude'  => '37.9755648',
				'longitude' => '23.7348324',
				'zoom'      => 5,
			),
			'duration'                        => '3',
			'duration_time'                   => 'Day',
			'tour_types'                      => array(),
			'night'                           => '0',
			'night_count'                     => '',
			'group_size'                      => '14',
			'language'                        => 'English',
			'refund_des'                      => '',
			'highlights-section-title'        => 'Highlights',
			'additional_information'          => '',
			'hightlights_thumbnail'           => '',
			'features'                        => array(),
			'contact-info-section-title'      => 'Contact Information',
			'tour-extra'                      => array(),
			'pricing'                         => 'person',
			'adult_price'                     => '90',
			'child_price'                     => '80',
			'infant_price'                    => '40',
			'group_price'                     => '',
			'package_pricing'                 => array(),
			'min_person'                      => '',
			'max_person'                      => '',
			'allow_discount'                  => '0',
			'discount_type'                   => 'none',
			'discount_price'                  => '',
			'disable_adult_price'             => '0',
			'disable_child_price'             => '0',
			'disable_infant_price'            => '0',
			'allow_deposit'                   => '0',
			'deposit_type'                    => 'none',
			'deposit_amount'                  => '',
			'type'                            => 'continuous',
			'custom_avail'                    => '0',
			'custom_pricing_by'               => 'person',
			'cont_custom_date'                => array(),
			'cont_min_people'                 => '',
			'cont_max_people'                 => '',
			'cont_max_capacity'               => '',
			'allowed_time'                    => array(),
			'disabled_day'                    => array(),
			'disable_range'                   => array(),
			'disable_specific'                => '',
			'fixed_availability'              => array(
				'date'     => array( 'from' => '', 'to' => '' ),
				'min_seat' => '',
				'max_seat' => '',
			),
			'min_days_before_book'            => '',
			'disable_same_day'                => '0',
			'tour-traveler-info'              => '0',
			'booking-by'                      => '1',
			'booking-url'                     => '',
			'booking-attribute'               => '',
			'booking-query'                   => '',
			'inc'                             => array(
				array( 'inc' => 'Specialized bilingual guide' ),
				array( 'inc' => 'Entrance fees' ),
			),
			'inc_icon'                        => 'fa fa-check',
			'exc'                             => array(
				array( 'exc' => 'Travel insurance' ),
				array( 'exc' => 'Personal expenses' ),
			),
			'exc_icon'                        => 'fa fa-times',
			'include-exclude-bg'              => '',
			'itinerary-section-title'         => 'Travel Itinerary',
			'itinerary'                       => array(),
			'itenary_download_glbal_settings' => 'custom',
			'itinerary-downloader'            => '0',
			'itinerary-downloader-title'      => 'Want to read it later?',
			'itinerary-downloader-desc'       => 'Download this tour\'s PDF brochure and start your planning offline.',
			'itinerary-downloader-button'     => 'Download Now',
			'tour_thumbnail_height'           => '',
			'tour_thumbnail_width'            => '',
			'company_logo'                    => '',
			'company_desc'                    => '',
			'company_email'                   => '',
			'company_address'                 => '',
			'company_phone'                   => '',
			'itinerary-expert'                => '0',
			'expert_label'                    => '',
			'expert_name'                     => '',
			'expert_email'                    => '',
			'expert_phone'                    => '',
			'expert_logo'                     => '',
			'itinerary-expert-viber'          => '0',
			'itinerary-expert-whatsapp'       => '0',
			'faq-section-title'               => 'Frequently Asked Questions',
			'faqs'                            => array(),
			'tc-section-title'                => 'Tour Terms & Conditions',
			'terms_conditions'                => '',
			't-review'                        => '0',
			't-share'                         => '0',
			't-related'                       => '0',
			'booking-section-title'           => 'Book This Tour',
			'description-section-title'       => 'Description',
			'map-section-title'               => 'Maps',
			'review-section-title'            => 'Average Guest Reviews',
			't-enquiry-section'               => '0',
			't-enquiry-option-title'          => 'Have a question in mind',
			't-enquiry-option-content'        => 'Looking for more info? Send a question to find out more.',
			't-enquiry-option-btn'            => 'Ask a Question',
		);
	}

	private function get_add_tour_example_request() {
		$payload = array(
			'title'           => 'City Walking Tour',
			'content'         => 'Explore the city on foot with our guided walking tour.',
			'featured_media'  => 43,
			'tourDestination' => array( 10, 12 ),
			'tourAttraction'  => array( 5 ),
			'tourActivities'  => array( 3 ),
			'tf_tours_opt'    => $this->get_tour_opt_example_payload(),
		);
		return 'POST /wp-json/tf/v1/add-tour' . "\n" . 'X-API-Key: your-api-key' . "\n" . 'Content-Type: application/json' . "\n\n" . wp_json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_update_tour_example_request() {
		$payload = array(
			'id'              => 777,
			'title'           => 'City Walking Tour Updated',
			'content'         => 'Updated tour description with all new details.',
			'featured_media'  => 43,
			'tourDestination' => array( 10, 12 ),
			'tourAttraction'  => array( 5 ),
			'tourActivities'  => array( 3 ),
			'tf_tours_opt'    => $this->get_tour_opt_example_payload(),
		);
		return 'POST /wp-json/tf/v1/update-tour' . "\n" . 'X-API-Key: your-api-key' . "\n" . 'Content-Type: application/json' . "\n\n" . wp_json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_apartment_opt_example_payload() {
		return array(
			'apartment_gallery'         => '60,61,62',
			'apartment_as_featured'     => '0',
			'featured_text'             => 'Hot Deal',
			'is_taxable'                => '0',
			'taxable_class'             => 'standard',
			'location_title'            => '',
			'map'                       => array(
				'address'   => '123 Main Street, New York, USA',
				'latitude'  => '40.7128',
				'longitude' => '-74.0060',
				'zoom'      => 15,
			),
			'surroundings_sec_title'    => '',
			'surroundings_subtitle'     => '',
			'surroundings_places'       => array(),
			'booking_form_title'        => '',
			'pricing_type'              => 'per_night',
			'price_per_night'           => '120',
			'adult_price'               => '',
			'child_price'               => '',
			'infant_price'              => '',
			'min_stay'                  => '',
			'max_adults'                => '',
			'max_children'              => '',
			'max_infants'               => '',
			'additional_fees'           => array(),
			'discount_type'             => 'none',
			'discount'                  => '',
			'booking-by'                => '1',
			'allow_deposit'             => '0',
			'deposit_type'              => 'percent',
			'deposit_amount'            => '',
			'booking-url'               => '',
			'booking-attribute'         => '',
			'booking-query'             => '',
			'enable_availability'       => '0',
			'apt_availability'          => '',
			'ical_url'                  => '',
			'room_details_title'        => '',
			'rooms'                     => array(),
			'highlights_title'          => '',
			'highlights'                => array(),
			'amenities_title'           => '',
			'amenities'                 => array(),
			'house_rules_title'         => '',
			'house_rules'               => array(),
			'faq_title'                 => '',
			'faq_desc'                  => '',
			'faq'                       => array(),
			'terms_title'               => '',
			'terms_and_conditions'      => '',
			'disable-apartment-review'  => '0',
			'disable-apartment-share'   => '0',
			'disable-related-apartment' => '0',
			'description_title'         => '',
			'review-section-title'      => '',
			'related_apartment_title'   => '',
			'enquiry-section'           => '1',
			'enquiry-title'             => '',
			'enquiry-content'           => '',
			'enquiry-btn'               => '',
		);
	}

	private function get_apartments_example_response() {
		return wp_json_encode( $this->get_apartments_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_apartments_example_payload() {
		return array(
			'apartments' => array(
				array(
					'id'                 => 88,
					'permalink'          => 'https://example.com/apartments/city-center-apartment/',
					'title'              => 'City Center Apartment',
					'content'            => 'Apartment description content.',
					'status'             => 'publish',
					'author'             => 'admin',
					'apartment_location' => 'New York',
					'apartment_type'     => 'Studio',
					'date'               => 'January 15, 2024',
					'featured_image'     => 'https://example.com/uploads/apartment-featured.jpg',
					'tf_apartment_opt'   => $this->get_apartment_opt_example_payload(),
					'reviews'            => array(
						'apartment_reviews' => 0,
						'review_text'       => '',
					),
					'start_price'        => '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>120.00</bdi></span>',
				),
			),
			'total' => 3,
		);
	}

	private function get_add_apartment_example_request() {
		$payload = array(
			'title'              => 'City Center Apartment',
			'content'            => 'Modern 2-bedroom apartment in city center.',
			'featured_media'     => 60,
			'apartmentLocations' => array( 12 ),
			'apartmentTypes'     => array( 4 ),
			'tf_apartment_opt'   => $this->get_apartment_opt_example_payload(),
		);
		return 'POST /wp-json/tf/v1/add-apartment' . "\n" . 'X-API-Key: your-api-key' . "\n" . 'Content-Type: application/json' . "\n\n" . wp_json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_update_apartment_example_request() {
		$payload = array(
			'id'                 => 888,
			'title'              => 'City Center Apartment Updated',
			'content'            => 'Updated apartment description.',
			'featured_media'     => 60,
			'apartmentLocations' => array( 12 ),
			'apartmentTypes'     => array( 4 ),
			'tf_apartment_opt'   => $this->get_apartment_opt_example_payload(),
		);
		return 'POST /wp-json/tf/v1/update-apartment' . "\n" . 'X-API-Key: your-api-key' . "\n" . 'Content-Type: application/json' . "\n\n" . wp_json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_carrental_opt_example_payload() {
		return array(
			'car_gallery'            => '70,71,72',
			'tf_single_car_layout_opt' => 'global',
			'tf_single_car_template' => 'design-1',
			'location_title'         => 'Location',
			'map'                    => array(
				'address'   => 'Dhaka, Bangladesh',
				'latitude'  => '23.8103',
				'longitude' => '90.4125',
			),
			'car_info_sec_title'     => 'Car info',
			'car_as_featured'        => '0',
			'featured_text'          => 'Hot Deal',
			'passengers'             => '5',
			'baggage'                => '3',
			'auto_transmission'      => '0',
			'unlimited_mileage'      => '0',
			'mileage_type'           => 'km',
			'mileage'                => '',
			'brands'                 => '',
			'fuel_types'             => '',
			'engine_year'            => '',
			'pay_pickup'             => '0',
			'shuttle_car'            => '0',
			'shuttle_car_fee_type'   => 'free',
			'shuttle_car_fee'        => '',
			'fuel_included'          => '',
			'driver_included'        => '0',
			'car_driverinfo_section' => '0',
			'driver_sec_title'       => 'Driver details',
			'driver_name'            => '',
			'driver_email'           => '',
			'driver_phone'           => '',
			'driver_age'             => '',
			'driver_address'         => '',
			'driver_image'           => '',
			'car_custom_info'        => array(),
			'benefits_section'       => '0',
			'benefits_sec_title'     => 'Benefits',
			'benefits'               => array(),
			'inc_exc_section'        => '0',
			'inc_sec_title'          => 'Include',
			'inc'                    => array(),
			'inc_icon'               => '',
			'exc_sec_title'          => 'Exclude',
			'exc'                    => array(),
			'exc_icon'               => '',
			'badge'                  => array(),
			'information_section'    => '0',
			'owner_sec_title'        => 'Renters Information',
			'owner_name'             => '',
			'email'                  => '',
			'phone'                  => '',
			'website'                => '',
			'fax'                    => '',
			'owner_image'            => '',
			'price_by'               => 'day',
			'car_rent'               => '75',
			'custom_availability'    => '0',
			'pricing_type'           => 'day_hour',
			'day_prices'             => array(),
			'date_prices'            => array(),
			'discount_type'          => 'none',
			'discount_price'         => '',
			'car_numbers'            => '',
			'allow_deposit'          => '0',
			'deposit_type'           => 'none',
			'deposit_amount'         => '',
			'car_extra_sec_title'    => 'Add extras',
			'extras'                 => array(),
			'protection_section'     => '0',
			'protection_tab_title'   => 'Protection',
			'protection_content'     => '',
			'protections'            => array(),
			'instructions_section'   => '0',
			'instructions_content'   => '',
			'cancellation_section'   => '0',
			'calcellation_policy'    => array(),
			'booking-by'             => '1',
			'booking-url'            => '',
			'booking-attribute'      => '',
			'booking-query'          => 'pickup={pickup}&dropoff={dropoff}&pickup_date={pickup_date}&dropoff_date={dropoff_date}',
			'is_taxable'             => '0',
			'taxable_class'          => 'standard',
			'faq_sec_title'          => 'FAQs',
			'faq'                    => array(),
			'car-tc-section-title'   => '',
			'terms_conditions'       => array(),
			'review_sec_title'       => 'Review Scores',
			'c-share'                => '0',
			'c-wishlist'             => '0',
		);
	}

	private function get_car_rentals_example_response() {
		return wp_json_encode( $this->get_car_rentals_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_car_rentals_example_payload() {
		return array(
			'rentals' => array(
				array(
					'id'                 => 99,
					'permalink'          => 'https://example.com/car-rentals/toyota-suv/',
					'title'              => 'Toyota SUV',
					'content'            => 'Comfortable Toyota SUV available for daily rental.',
					'status'             => 'publish',
					'author'             => 'admin',
					'carrental_location' => 'Dhaka',
					'carrental_brand'    => 'Toyota',
					'date'               => 'January 15, 2024',
					'featured_image'     => 'https://example.com/uploads/car-featured.jpg',
					'tf_carrental_opt'   => $this->get_carrental_opt_example_payload(),
					'reviews'            => array(
						'car_reviews' => 0,
						'review_text' => '',
					),
					'start_price'        => '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>75.00</bdi></span>',
				),
			),
			'total' => 4,
		);
	}

	private function get_add_rental_example_request() {
		$payload = array(
			'title'               => 'Toyota SUV',
			'content'             => 'Comfortable Toyota SUV available for daily rental.',
			'featured_media'      => 70,
			'carRentalLocations'  => array( 9 ),
			'carRentalCategories' => array( 3 ),
			'tf_carrental_opt'    => $this->get_carrental_opt_example_payload(),
		);
		return 'POST /wp-json/tf/v1/add-rental' . "\n" . 'X-API-Key: your-api-key' . "\n" . 'Content-Type: application/json' . "\n\n" . wp_json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_update_rental_example_request() {
		$payload = array(
			'id'                  => 999,
			'title'               => 'Toyota SUV Updated',
			'content'             => 'Updated rental description.',
			'featured_media'      => 70,
			'carRentalLocations'  => array( 9 ),
			'carRentalCategories' => array( 3 ),
			'tf_carrental_opt'    => $this->get_carrental_opt_example_payload(),
		);
		return 'POST /wp-json/tf/v1/update-rental' . "\n" . 'X-API-Key: your-api-key' . "\n" . 'Content-Type: application/json' . "\n\n" . wp_json_encode( $payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_tour_availability_example_response() {
		return wp_json_encode( $this->get_tour_availability_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_tour_availability_example_payload() {
		return array(
			array(
				'check_in'           => '2026/05/01',
				'check_out'          => '2026/05/02',
				'pricing_type'       => 'person',
				'price'              => '',
				'adult_price'        => '30',
				'child_price'        => '20',
				'infant_price'       => '10',
				'min_person'         => '1',
				'max_person'         => '10',
				'max_capacity'       => '100',
				'allowed_time'       => array(
					'time'               => array( '' ),
					'cont_max_capacity'  => array( '' ),
				),
				'status'             => 'available',
				'title'              => 'Adult: $30.00, Child: $20.00, Infant: $10.00',
				'start'              => '2026-05-01',
				'end'                => '2026-05-03',
			),
		);
	}

	private function get_apartment_availability_example_response() {
		return wp_json_encode( $this->get_apartment_availability_example_payload(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
	}

	private function get_apartment_availability_example_payload() {
		return array(
			array(
				'check_in'      => '2026/05/01',
				'check_out'     => '2026/05/01',
				'pricing_type'  => 'per_night',
				'price'         => '50',
				'adult_price'   => '',
				'child_price'   => '',
				'infant_price'  => '',
				'status'        => 'available',
				'editable'      => false,
				'start'         => '2026-05-01',
				'title'         => 'Price: $50.00',
			),
			array(
				'check_in'      => '2026/05/02',
				'check_out'     => '2026/05/02',
				'pricing_type'  => 'per_night',
				'price'         => '50',
				'adult_price'   => '',
				'child_price'   => '',
				'infant_price'  => '',
				'status'        => 'available',
				'editable'      => false,
				'start'         => '2026-05-02',
				'title'         => 'Price: $50.00',
			),
		);
	}
}
