<?php
function fontawesome_six_icons() {
	$icons = array(
		'fa-solid fa-fill-drip',
		'fa-solid fa-arrows-to-circle',
		'fa-solid fa-chevron-circle-right fa-circle-chevron-right',
		'fa-solid fa-at',
		'fa-solid fa-trash-alt fa-trash-can',
		'fa-solid fa-text-height',
		'fa-solid fa-user-times fa-user-xmark',
		'fa-solid fa-stethoscope',
		'fa-solid fa-comment-alt fa-message',
		'fa-solid fa-info',
		'fa-solid fa-compress-alt fa-down-left-and-up-right-to-center',
		'fa-solid fa-explosion',
		'fa-solid fa-file-alt fa-file-lines fa-file-text',
		'fa-solid fa-wave-square',
		'fa-solid fa-ring',
		'fa-solid fa-building-un',
		'fa-solid fa-dice-three',
		'fa-solid fa-calendar-alt fa-calendar-days',
		'fa-solid fa-anchor-circle-check',
		'fa-solid fa-building-circle-arrow-right',
		'fa-solid fa-volleyball-ball fa-volleyball',
		'fa-solid fa-arrows-up-to-line',
		'fa-solid fa-sort-desc fa-sort-down',
		'fa-solid fa-circle-minus fa-minus-circle',
		'fa-solid fa-door-open',
		'fa-solid fa-right-from-bracket fa-sign-out-alt',
		'fa-solid fa-atom',
		'fa-solid fa-soap',
		'fa-solid fa-heart-music-camera-bolt fa-icons',
		'fa-solid fa-microphone-alt-slash fa-microphone-lines-slash',
		'fa-solid fa-bridge-circle-check',
		'fa-solid fa-pump-medical',
		'fa-solid fa-fingerprint',
		'fa-solid fa-hand-point-right',
		'fa-solid fa-magnifying-glass-location fa-search-location',
		'fa-solid fa-forward-step fa-step-forward',
		'fa-solid fa-face-smile-beam fa-smile-beam',
		'fa-solid fa-flag-checkered',
		'fa-solid fa-football-ball fa-football',
		'fa-solid fa-school-circle-exclamation',
		'fa-solid fa-crop',
		'fa-solid fa-angle-double-down fa-angles-down',
		'fa-solid fa-users-rectangle',
		'fa-solid fa-people-roof',
		'fa-solid fa-people-line',
		'fa-solid fa-beer-mug-empty fa-beer',
		'fa-solid fa-diagram-predecessor',
		'fa-solid fa-arrow-up-long fa-long-arrow-up',
		'fa-solid fa-burn fa-fire-flame-simple',
		'fa-solid fa-male fa-person',
		'fa-solid fa-laptop',
		'fa-solid fa-file-csv',
		'fa-solid fa-menorah',
		'fa-solid fa-truck-plane',
		'fa-solid fa-record-vinyl',
		'fa-solid fa-face-grin-stars fa-grin-stars',
		'fa-solid fa-bong',
		'fa-solid fa-pastafarianism fa-spaghetti-monster-flying',
		'fa-solid fa-arrow-down-up-across-line',
		'fa-solid fa-spoon fa-utensil-spoon',
		'fa-solid fa-jar-wheat',
		'fa-solid fa-envelopes-bulk fa-mail-bulk',
		'fa-solid fa-file-circle-exclamation',
		'fa-solid fa-circle-h fa-hospital-symbol',
		'fa-solid fa-pager',
		'fa-solid fa-address-book fa-contact-book',
		'fa-solid fa-strikethrough',
		'fa-solid fa-k',
		'fa-solid fa-landmark-flag',
		'fa-solid fa-pencil-alt fa-pencil',
		'fa-solid fa-backward',
		'fa-solid fa-caret-right',
		'fa-solid fa-comments',
		'fa-solid fa-file-clipboard fa-paste',
		'fa-solid fa-code-pull-request',
		'fa-solid fa-clipboard-list',
		'fa-solid fa-truck-loading fa-truck-ramp-box',
		'fa-solid fa-user-check',
		'fa-solid fa-vial-virus',
		'fa-solid fa-sheet-plastic',
		'fa-solid fa-blog',
		'fa-solid fa-user-ninja',
		'fa-solid fa-person-arrow-up-from-line',
		'fa-solid fa-scroll-torah fa-torah',
		'fa-solid fa-broom-ball fa-quidditch-broom-ball fa-quidditch',
		'fa-solid fa-toggle-off',
		'fa-solid fa-archive fa-box-archive',
		'fa-solid fa-person-drowning',
		'fa-solid fa-arrow-down-9-1 fa-sort-numeric-desc fa-sort-numeric-down-alt',
		'fa-solid fa-face-grin-tongue-squint fa-grin-tongue-squint',
		'fa-solid fa-spray-can',
		'fa-solid fa-truck-monster',
		'fa-solid fa-w',
		'fa-solid fa-earth-africa fa-globe-africa',
		'fa-solid fa-rainbow',
		'fa-solid fa-circle-notch',
		'fa-solid fa-tablet-alt fa-tablet-screen-button',
		'fa-solid fa-paw',
		'fa-solid fa-cloud',
		'fa-solid fa-trowel-bricks',
		'fa-solid fa-face-flushed fa-flushed',
		'fa-solid fa-hospital-user',
		'fa-solid fa-tent-arrow-left-right',
		'fa-solid fa-gavel fa-legal',
		'fa-solid fa-binoculars',
		'fa-solid fa-microphone-slash',
		'fa-solid fa-box-tissue',
		'fa-solid fa-motorcycle',
		'fa-solid fa-bell-concierge fa-concierge-bell',
		'fa-solid fa-pen-ruler fa-pencil-ruler',
		'fa-solid fa-people-arrows-left-right fa-people-arrows',
		'fa-solid fa-mars-and-venus-burst',
		'fa-solid fa-caret-square-right fa-square-caret-right',
		'fa-solid fa-cut fa-scissors',
		'fa-solid fa-sun-plant-wilt',
		'fa-solid fa-toilets-portable',
		'fa-solid fa-hockey-puck',
		'fa-solid fa-table',
		'fa-solid fa-magnifying-glass-arrow-right',
		'fa-solid fa-digital-tachograph fa-tachograph-digital',
		'fa-solid fa-users-slash',
		'fa-solid fa-clover',
		'fa-solid fa-mail-reply fa-reply',
		'fa-solid fa-star-and-crescent',
		'fa-solid fa-house-fire',
		'fa-solid fa-minus-square fa-square-minus',
		'fa-solid fa-helicopter',
		'fa-solid fa-compass',
		'fa-solid fa-caret-square-down fa-square-caret-down',
		'fa-solid fa-file-circle-question',
		'fa-solid fa-laptop-code',
		'fa-solid fa-swatchbook',
		'fa-solid fa-prescription-bottle',
		'fa-solid fa-bars fa-navicon',
		'fa-solid fa-people-group',
		'fa-solid fa-hourglass-3 fa-hourglass-end',
		'fa-solid fa-heart-broken fa-heart-crack',
		'fa-solid fa-external-link-square-alt fa-square-up-right',
		'fa-solid fa-face-kiss-beam fa-kiss-beam',
		'fa-solid fa-film',
		'fa-solid fa-ruler-horizontal',
		'fa-solid fa-people-robbery',
		'fa-solid fa-lightbulb',
		'fa-solid fa-caret-left',
		'fa-solid fa-circle-exclamation fa-exclamation-circle',
		'fa-solid fa-school-circle-xmark',
		'fa-solid fa-arrow-right-from-bracket fa-sign-out',
		'fa-solid fa-chevron-circle-down fa-circle-chevron-down',
		'fa-solid fa-unlock-alt fa-unlock-keyhole',
		'fa-solid fa-cloud-showers-heavy',
		'fa-solid fa-headphones-alt fa-headphones-simple',
		'fa-solid fa-sitemap',
		'fa-solid fa-circle-dollar-to-slot fa-donate',
		'fa-solid fa-memory',
		'fa-solid fa-road-spikes',
		'fa-solid fa-fire-burner',
		'fa-solid fa-flag',
		'fa-solid fa-hanukiah',
		'fa-solid fa-feather',
		'fa-solid fa-volume-down fa-volume-low',
		'fa-solid fa-comment-slash',
		'fa-solid fa-cloud-sun-rain',
		'fa-solid fa-compress',
		'fa-solid fa-wheat-alt fa-wheat-awn',
		'fa-solid fa-ankh',
		'fa-solid fa-hands-holding-child',
		'fa-solid fa-asterisk',
		'fa-solid fa-check-square fa-square-check',
		'fa-solid fa-peseta-sign',
		'fa-solid fa-header fa-heading',
		'fa-solid fa-ghost',
		'fa-solid fa-list-squares fa-list',
		'fa-solid fa-phone-square-alt fa-square-phone-flip',
		'fa-solid fa-cart-plus',
		'fa-solid fa-gamepad',
		'fa-solid fa-circle-dot fa-dot-circle',
		'fa-solid fa-dizzy fa-face-dizzy',
		'fa-solid fa-egg',
		'fa-solid fa-house-medical-circle-xmark',
		'fa-solid fa-campground',
		'fa-solid fa-folder-plus',
		'fa-solid fa-futbol-ball fa-futbol fa-soccer-ball',
		'fa-solid fa-paint-brush fa-paintbrush',
		'fa-solid fa-lock',
		'fa-solid fa-gas-pump',
		'fa-solid fa-hot-tub-person fa-hot-tub',
		'fa-solid fa-map-location fa-map-marked',
		'fa-solid fa-house-flood-water',
		'fa-solid fa-tree',
		'fa-solid fa-bridge-lock',
		'fa-solid fa-sack-dollar',
		'fa-solid fa-edit fa-pen-to-square',
		'fa-solid fa-car-side',
		'fa-solid fa-share-alt fa-share-nodes',
		'fa-solid fa-heart-circle-minus',
		'fa-solid fa-hourglass-2 fa-hourglass-half',
		'fa-solid fa-microscope',
		'fa-solid fa-sink',
		'fa-solid fa-bag-shopping fa-shopping-bag',
		'fa-solid fa-arrow-down-z-a fa-sort-alpha-desc fa-sort-alpha-down-alt',
		'fa-solid fa-mitten',
		'fa-solid fa-person-rays',
		'fa-solid fa-users',
		'fa-solid fa-eye-slash',
		'fa-solid fa-flask-vial',
		'fa-solid fa-hand-paper fa-hand',
		'fa-solid fa-om',
		'fa-solid fa-worm',
		'fa-solid fa-house-circle-xmark',
		'fa-solid fa-plug',
		'fa-solid fa-chevron-up',
		'fa-solid fa-hand-spock',
		'fa-solid fa-stopwatch',
		'fa-solid fa-face-kiss fa-kiss',
		'fa-solid fa-bridge-circle-xmark',
		'fa-solid fa-face-grin-tongue fa-grin-tongue',
		'fa-solid fa-chess-bishop',
		'fa-solid fa-face-grin-wink fa-grin-wink',
		'fa-solid fa-deaf fa-deafness fa-ear-deaf fa-hard-of-hearing',
		'fa-solid fa-road-circle-check',
		'fa-solid fa-dice-five',
		'fa-solid fa-rss-square fa-square-rss',
		'fa-solid fa-land-mine-on',
		'fa-solid fa-i-cursor',
		'fa-solid fa-stamp',
		'fa-solid fa-stairs',
		'fa-solid fa-i',
		'fa-solid fa-hryvnia-sign fa-hryvnia',
		'fa-solid fa-pills',
		'fa-solid fa-face-grin-wide fa-grin-alt',
		'fa-solid fa-tooth',
		'fa-solid fa-v',
		'fa-solid fa-bangladeshi-taka-sign',
		'fa-solid fa-bicycle',
		'fa-solid fa-rod-asclepius fa-rod-snake fa-staff-aesculapius fa-staff-snake',
		'fa-solid fa-head-side-cough-slash',
		'fa-solid fa-ambulance fa-truck-medical',
		'fa-solid fa-wheat-awn-circle-exclamation',
		'fa-solid fa-snowman',
		'fa-solid fa-mortar-pestle',
		'fa-solid fa-road-barrier',
		'fa-solid fa-school',
		'fa-solid fa-igloo',
		'fa-solid fa-joint',
		'fa-solid fa-angle-right',
		'fa-solid fa-horse',
		'fa-solid fa-q',
		'fa-solid fa-g',
		'fa-solid fa-notes-medical',
		'fa-solid fa-temperature-2 fa-temperature-half fa-thermometer-2 fa-thermometer-half',
		'fa-solid fa-dong-sign',
		'fa-solid fa-capsules',
		'fa-solid fa-poo-bolt fa-poo-storm',
		'fa-solid fa-face-frown-open fa-frown-open',
		'fa-solid fa-hand-point-up',
		'fa-solid fa-money-bill',
		'fa-solid fa-bookmark',
		'fa-solid fa-align-justify',
		'fa-solid fa-umbrella-beach',
		'fa-solid fa-helmet-un',
		'fa-solid fa-bullseye',
		'fa-solid fa-bacon',
		'fa-solid fa-hand-point-down',
		'fa-solid fa-arrow-up-from-bracket',
		'fa-solid fa-folder-blank fa-folder',
		'fa-solid fa-file-medical-alt fa-file-waveform',
		'fa-solid fa-radiation',
		'fa-solid fa-chart-simple',
		'fa-solid fa-mars-stroke',
		'fa-solid fa-vial',
		'fa-solid fa-dashboard fa-gauge-med fa-gauge fa-tachometer-alt-average',
		'fa-solid fa-magic-wand-sparkles fa-wand-magic-sparkles',
		'fa-solid fa-e',
		'fa-solid fa-pen-alt fa-pen-clip',
		'fa-solid fa-bridge-circle-exclamation',
		'fa-solid fa-user',
		'fa-solid fa-school-circle-check',
		'fa-solid fa-dumpster',
		'fa-solid fa-shuttle-van fa-van-shuttle',
		'fa-solid fa-building-user',
		'fa-solid fa-caret-square-left fa-square-caret-left',
		'fa-solid fa-highlighter',
		'fa-solid fa-key',
		'fa-solid fa-bullhorn',
		'fa-solid fa-globe',
		'fa-solid fa-synagogue',
		'fa-solid fa-person-half-dress',
		'fa-solid fa-road-bridge',
		'fa-solid fa-location-arrow',
		'fa-solid fa-c',
		'fa-solid fa-tablet-button',
		'fa-solid fa-building-lock',
		'fa-solid fa-pizza-slice',
		'fa-solid fa-money-bill-wave',
		'fa-solid fa-area-chart fa-chart-area',
		'fa-solid fa-house-flag',
		'fa-solid fa-person-circle-minus',
		'fa-solid fa-ban fa-cancel',
		'fa-solid fa-camera-rotate',
		'fa-solid fa-air-freshener fa-spray-can-sparkles',
		'fa-solid fa-star',
		'fa-solid fa-repeat',
		'fa-solid fa-cross',
		'fa-solid fa-box',
		'fa-solid fa-venus-mars',
		'fa-solid fa-arrow-pointer fa-mouse-pointer',
		'fa-solid fa-expand-arrows-alt fa-maximize',
		'fa-solid fa-charging-station',
		'fa-solid fa-shapes fa-triangle-circle-square',
		'fa-solid fa-random fa-shuffle',
		'fa-solid fa-person-running fa-running',
		'fa-solid fa-mobile-retro',
		'fa-solid fa-grip-lines-vertical',
		'fa-solid fa-spider',
		'fa-solid fa-hands-bound',
		'fa-solid fa-file-invoice-dollar',
		'fa-solid fa-plane-circle-exclamation',
		'fa-solid fa-x-ray',
		'fa-solid fa-spell-check',
		'fa-solid fa-slash',
		'fa-solid fa-computer-mouse fa-mouse',
		'fa-solid fa-arrow-right-to-bracket fa-sign-in',
		'fa-solid fa-shop-slash fa-store-alt-slash',
		'fa-solid fa-server',
		'fa-solid fa-virus-covid-slash',
		'fa-solid fa-shop-lock',
		'fa-solid fa-hourglass-1 fa-hourglass-start',
		'fa-solid fa-blender-phone',
		'fa-solid fa-building-wheat',
		'fa-solid fa-person-breastfeeding',
		'fa-solid fa-right-to-bracket fa-sign-in-alt',
		'fa-solid fa-venus',
		'fa-solid fa-passport',
		'fa-solid fa-heart-pulse fa-heartbeat',
		'fa-solid fa-people-carry-box fa-people-carry',
		'fa-solid fa-temperature-high',
		'fa-solid fa-microchip',
		'fa-solid fa-crown',
		'fa-solid fa-weight-hanging',
		'fa-solid fa-xmarks-lines',
		'fa-solid fa-file-prescription',
		'fa-solid fa-weight-scale fa-weight',
		'fa-solid fa-user-friends fa-user-group',
		'fa-solid fa-arrow-up-a-z fa-sort-alpha-up',
		'fa-solid fa-chess-knight',
		'fa-solid fa-face-laugh-squint fa-laugh-squint',
		'fa-solid fa-wheelchair',
		'fa-solid fa-arrow-circle-up fa-circle-arrow-up',
		'fa-solid fa-toggle-on',
		'fa-solid fa-person-walking fa-walking',
		'fa-solid fa-l',
		'fa-solid fa-fire',
		'fa-solid fa-bed-pulse fa-procedures',
		'fa-solid fa-shuttle-space fa-space-shuttle',
		'fa-solid fa-face-laugh fa-laugh',
		'fa-solid fa-folder-open',
		'fa-solid fa-heart-circle-plus',
		'fa-solid fa-code-fork',
		'fa-solid fa-city',
		'fa-solid fa-microphone-alt fa-microphone-lines',
		'fa-solid fa-pepper-hot',
		'fa-solid fa-unlock',
		'fa-solid fa-colon-sign',
		'fa-solid fa-headset',
		'fa-solid fa-store-slash',
		'fa-solid fa-road-circle-xmark',
		'fa-solid fa-user-minus',
		'fa-solid fa-mars-stroke-up fa-mars-stroke-v',
		'fa-solid fa-champagne-glasses fa-glass-cheers',
		'fa-solid fa-clipboard',
		'fa-solid fa-house-circle-exclamation',
		'fa-solid fa-file-arrow-up fa-file-upload',
		'fa-solid fa-wifi-3 fa-wifi-strong fa-wifi',
		'fa-solid fa-bath fa-bathtub',
		'fa-solid fa-underline',
		'fa-solid fa-user-edit fa-user-pen',
		'fa-solid fa-signature',
		'fa-solid fa-stroopwafel',
		'fa-solid fa-bold',
		'fa-solid fa-anchor-lock',
		'fa-solid fa-building-ngo',
		'fa-solid fa-manat-sign',
		'fa-solid fa-not-equal',
		'fa-solid fa-border-style fa-border-top-left',
		'fa-solid fa-map-location-dot fa-map-marked-alt',
		'fa-solid fa-jedi',
		'fa-solid fa-poll fa-square-poll-vertical',
		'fa-solid fa-mug-hot',
		'fa-solid fa-battery-car fa-car-battery',
		'fa-solid fa-gift',
		'fa-solid fa-dice-two',
		'fa-solid fa-chess-queen',
		'fa-solid fa-glasses',
		'fa-solid fa-chess-board',
		'fa-solid fa-building-circle-check',
		'fa-solid fa-person-chalkboard',
		'fa-solid fa-mars-stroke-h fa-mars-stroke-right',
		'fa-solid fa-hand-back-fist fa-hand-rock',
		'fa-solid fa-caret-square-up fa-square-caret-up',
		'fa-solid fa-cloud-showers-water',
		'fa-solid fa-bar-chart fa-chart-bar',
		'fa-solid fa-hands-bubbles fa-hands-wash',
		'fa-solid fa-less-than-equal',
		'fa-solid fa-train',
		'fa-solid fa-eye-low-vision fa-low-vision',
		'fa-solid fa-crow',
		'fa-solid fa-sailboat',
		'fa-solid fa-window-restore',
		'fa-solid fa-plus-square fa-square-plus',
		'fa-solid fa-torii-gate',
		'fa-solid fa-frog',
		'fa-solid fa-bucket',
		'fa-solid fa-image',
		'fa-solid fa-microphone',
		'fa-solid fa-cow',
		'fa-solid fa-caret-up',
		'fa-solid fa-screwdriver',
		'fa-solid fa-folder-closed',
		'fa-solid fa-house-tsunami',
		'fa-solid fa-square-nfi',
		'fa-solid fa-arrow-up-from-ground-water',
		'fa-solid fa-glass-martini-alt fa-martini-glass',
		'fa-solid fa-rotate-back fa-rotate-backward fa-rotate-left fa-undo-alt',
		'fa-solid fa-columns fa-table-columns',
		'fa-solid fa-lemon',
		'fa-solid fa-head-side-mask',
		'fa-solid fa-handshake',
		'fa-solid fa-gem',
		'fa-solid fa-dolly-box fa-dolly',
		'fa-solid fa-smoking',
		'fa-solid fa-compress-arrows-alt fa-minimize',
		'fa-solid fa-monument',
		'fa-solid fa-snowplow',
		'fa-solid fa-angle-double-right fa-angles-right',
		'fa-solid fa-cannabis',
		'fa-solid fa-circle-play fa-play-circle',
		'fa-solid fa-tablets',
		'fa-solid fa-ethernet',
		'fa-solid fa-eur fa-euro-sign fa-euro',
		'fa-solid fa-chair',
		'fa-solid fa-check-circle fa-circle-check',
		'fa-solid fa-circle-stop fa-stop-circle',
		'fa-solid fa-compass-drafting fa-drafting-compass',
		'fa-solid fa-plate-wheat',
		'fa-solid fa-icicles',
		'fa-solid fa-person-shelter',
		'fa-solid fa-neuter',
		'fa-solid fa-id-badge',
		'fa-solid fa-marker',
		'fa-solid fa-face-laugh-beam fa-laugh-beam',
		'fa-solid fa-helicopter-symbol',
		'fa-solid fa-universal-access',
		'fa-solid fa-chevron-circle-up fa-circle-chevron-up',
		'fa-solid fa-lari-sign',
		'fa-solid fa-volcano',
		'fa-solid fa-person-walking-dashed-line-arrow-right',
		'fa-solid fa-gbp fa-pound-sign fa-sterling-sign',
		'fa-solid fa-viruses',
		'fa-solid fa-square-person-confined',
		'fa-solid fa-user-tie',
		'fa-solid fa-arrow-down-long fa-long-arrow-down',
		'fa-solid fa-tent-arrow-down-to-line',
		'fa-solid fa-certificate',
		'fa-solid fa-mail-reply-all fa-reply-all',
		'fa-solid fa-suitcase',
		'fa-solid fa-person-skating fa-skating',
		'fa-solid fa-filter-circle-dollar fa-funnel-dollar',
		'fa-solid fa-camera-retro',
		'fa-solid fa-arrow-circle-down fa-circle-arrow-down',
		'fa-solid fa-arrow-right-to-file fa-file-import',
		'fa-solid fa-external-link-square fa-square-arrow-up-right',
		'fa-solid fa-box-open',
		'fa-solid fa-scroll',
		'fa-solid fa-spa',
		'fa-solid fa-location-pin-lock',
		'fa-solid fa-pause',
		'fa-solid fa-hill-avalanche',
		'fa-solid fa-temperature-0 fa-temperature-empty fa-thermometer-0 fa-thermometer-empty',
		'fa-solid fa-bomb',
		'fa-solid fa-registered',
		'fa-solid fa-address-card fa-contact-card fa-vcard',
		'fa-solid fa-balance-scale-right fa-scale-unbalanced-flip',
		'fa-solid fa-subscript',
		'fa-solid fa-diamond-turn-right fa-directions',
		'fa-solid fa-burst',
		'fa-solid fa-house-laptop fa-laptop-house',
		'fa-solid fa-face-tired fa-tired',
		'fa-solid fa-money-bills',
		'fa-solid fa-smog',
		'fa-solid fa-crutch',
		'fa-solid fa-cloud-arrow-up fa-cloud-upload-alt fa-cloud-upload',
		'fa-solid fa-palette',
		'fa-solid fa-arrows-turn-right',
		'fa-solid fa-vest',
		'fa-solid fa-ferry',
		'fa-solid fa-arrows-down-to-people',
		'fa-solid fa-seedling fa-sprout',
		'fa-solid fa-arrows-alt-h fa-left-right',
		'fa-solid fa-boxes-packing',
		'fa-solid fa-arrow-circle-left fa-circle-arrow-left',
		'fa-solid fa-group-arrows-rotate',
		'fa-solid fa-bowl-food',
		'fa-solid fa-candy-cane',
		'fa-solid fa-arrow-down-wide-short fa-sort-amount-asc fa-sort-amount-down',
		'fa-solid fa-cloud-bolt fa-thunderstorm',
		'fa-solid fa-remove-format fa-text-slash',
		'fa-solid fa-face-smile-wink fa-smile-wink',
		'fa-solid fa-file-word',
		'fa-solid fa-file-powerpoint',
		'fa-solid fa-arrows-h fa-arrows-left-right',
		'fa-solid fa-house-lock',
		'fa-solid fa-cloud-arrow-down fa-cloud-download-alt fa-cloud-download',
		'fa-solid fa-children',
		'fa-solid fa-blackboard fa-chalkboard',
		'fa-solid fa-user-alt-slash fa-user-large-slash',
		'fa-solid fa-envelope-open',
		'fa-solid fa-handshake-alt-slash fa-handshake-simple-slash',
		'fa-solid fa-mattress-pillow',
		'fa-solid fa-guarani-sign',
		'fa-solid fa-arrows-rotate fa-refresh fa-sync',
		'fa-solid fa-fire-extinguisher',
		'fa-solid fa-cruzeiro-sign',
		'fa-solid fa-greater-than-equal',
		'fa-solid fa-shield-alt fa-shield-halved',
		'fa-solid fa-atlas fa-book-atlas',
		'fa-solid fa-virus',
		'fa-solid fa-envelope-circle-check',
		'fa-solid fa-layer-group',
		'fa-solid fa-arrows-to-dot',
		'fa-solid fa-archway',
		'fa-solid fa-heart-circle-check',
		'fa-solid fa-house-chimney-crack fa-house-damage',
		'fa-solid fa-file-archive fa-file-zipper',
		'fa-solid fa-square',
		'fa-solid fa-glass-martini fa-martini-glass-empty',
		'fa-solid fa-couch',
		'fa-solid fa-cedi-sign',
		'fa-solid fa-italic',
		'fa-solid fa-church',
		'fa-solid fa-comments-dollar',
		'fa-solid fa-democrat',
		'fa-solid fa-z',
		'fa-solid fa-person-skiing fa-skiing',
		'fa-solid fa-road-lock',
		'fa-solid fa-a',
		'fa-solid fa-temperature-arrow-down fa-temperature-down',
		'fa-solid fa-feather-alt fa-feather-pointed',
		'fa-solid fa-p',
		'fa-solid fa-snowflake',
		'fa-solid fa-newspaper',
		'fa-solid fa-ad fa-rectangle-ad',
		'fa-solid fa-arrow-circle-right fa-circle-arrow-right',
		'fa-solid fa-filter-circle-xmark',
		'fa-solid fa-locust',
		'fa-solid fa-sort fa-unsorted',
		'fa-solid fa-list-1-2 fa-list-numeric fa-list-ol',
		'fa-solid fa-person-dress-burst',
		'fa-solid fa-money-check-alt fa-money-check-dollar',
		'fa-solid fa-vector-square',
		'fa-solid fa-bread-slice',
		'fa-solid fa-language',
		'fa-solid fa-face-kiss-wink-heart fa-kiss-wink-heart',
		'fa-solid fa-filter',
		'fa-solid fa-question',
		'fa-solid fa-file-signature',
		'fa-solid fa-arrows-alt fa-up-down-left-right',
		'fa-solid fa-house-chimney-user',
		'fa-solid fa-hand-holding-heart',
		'fa-solid fa-puzzle-piece',
		'fa-solid fa-money-check',
		'fa-solid fa-star-half-alt fa-star-half-stroke',
		'fa-solid fa-code',
		'fa-solid fa-glass-whiskey fa-whiskey-glass',
		'fa-solid fa-building-circle-exclamation',
		'fa-solid fa-magnifying-glass-chart',
		'fa-solid fa-arrow-up-right-from-square fa-external-link',
		'fa-solid fa-cubes-stacked',
		'fa-solid fa-krw fa-won-sign fa-won',
		'fa-solid fa-virus-covid',
		'fa-solid fa-austral-sign',
		'fa-solid fa-f',
		'fa-solid fa-leaf',
		'fa-solid fa-road',
		'fa-solid fa-cab fa-taxi',
		'fa-solid fa-person-circle-plus',
		'fa-solid fa-chart-pie fa-pie-chart',
		'fa-solid fa-bolt-lightning',
		'fa-solid fa-sack-xmark',
		'fa-solid fa-file-excel',
		'fa-solid fa-file-contract',
		'fa-solid fa-fish-fins',
		'fa-solid fa-building-flag',
		'fa-solid fa-face-grin-beam fa-grin-beam',
		'fa-solid fa-object-ungroup',
		'fa-solid fa-poop',
		'fa-solid fa-location-pin fa-map-marker',
		'fa-solid fa-kaaba',
		'fa-solid fa-toilet-paper',
		'fa-solid fa-hard-hat fa-hat-hard fa-helmet-safety',
		'fa-solid fa-eject',
		'fa-solid fa-arrow-alt-circle-right fa-circle-right',
		'fa-solid fa-plane-circle-check',
		'fa-solid fa-face-rolling-eyes fa-meh-rolling-eyes',
		'fa-solid fa-object-group',
		'fa-solid fa-chart-line fa-line-chart',
		'fa-solid fa-mask-ventilator',
		'fa-solid fa-arrow-right',
		'fa-solid fa-map-signs fa-signs-post',
		'fa-solid fa-cash-register',
		'fa-solid fa-person-circle-question',
		'fa-solid fa-h',
		'fa-solid fa-tarp',
		'fa-solid fa-screwdriver-wrench fa-tools',
		'fa-solid fa-arrows-to-eye',
		'fa-solid fa-plug-circle-bolt',
		'fa-solid fa-heart',
		'fa-solid fa-mars-and-venus',
		'fa-solid fa-home-user fa-house-user',
		'fa-solid fa-dumpster-fire',
		'fa-solid fa-house-crack',
		'fa-solid fa-cocktail fa-martini-glass-citrus',
		'fa-solid fa-face-surprise fa-surprise',
		'fa-solid fa-bottle-water',
		'fa-solid fa-circle-pause fa-pause-circle',
		'fa-solid fa-toilet-paper-slash',
		'fa-solid fa-apple-alt fa-apple-whole',
		'fa-solid fa-kitchen-set',
		'fa-solid fa-r',
		'fa-solid fa-temperature-1 fa-temperature-quarter fa-thermometer-1 fa-thermometer-quarter',
		'fa-solid fa-cube',
		'fa-solid fa-bitcoin-sign',
		'fa-solid fa-shield-dog',
		'fa-solid fa-solar-panel',
		'fa-solid fa-lock-open',
		'fa-solid fa-elevator',
		'fa-solid fa-money-bill-transfer',
		'fa-solid fa-money-bill-trend-up',
		'fa-solid fa-house-flood-water-circle-arrow-right',
		'fa-solid fa-poll-h fa-square-poll-horizontal',
		'fa-solid fa-circle',
		'fa-solid fa-backward-fast fa-fast-backward',
		'fa-solid fa-recycle',
		'fa-solid fa-user-astronaut',
		'fa-solid fa-plane-slash',
		'fa-solid fa-trademark',
		'fa-solid fa-basketball-ball fa-basketball',
		'fa-solid fa-satellite-dish',
		'fa-solid fa-arrow-alt-circle-up fa-circle-up',
		'fa-solid fa-mobile-alt fa-mobile-screen-button',
		'fa-solid fa-volume-high fa-volume-up',
		'fa-solid fa-users-rays',
		'fa-solid fa-wallet',
		'fa-solid fa-clipboard-check',
		'fa-solid fa-file-audio',
		'fa-solid fa-burger fa-hamburger',
		'fa-solid fa-wrench',
		'fa-solid fa-bugs',
		'fa-solid fa-rupee-sign fa-rupee',
		'fa-solid fa-file-image',
		'fa-solid fa-circle-question fa-question-circle',
		'fa-solid fa-plane-departure',
		'fa-solid fa-handshake-slash',
		'fa-solid fa-book-bookmark',
		'fa-solid fa-code-branch',
		'fa-solid fa-hat-cowboy',
		'fa-solid fa-bridge',
		'fa-solid fa-phone-alt fa-phone-flip',
		'fa-solid fa-truck-front',
		'fa-solid fa-cat',
		'fa-solid fa-anchor-circle-exclamation',
		'fa-solid fa-truck-field',
		'fa-solid fa-route',
		'fa-solid fa-clipboard-question',
		'fa-solid fa-panorama',
		'fa-solid fa-comment-medical',
		'fa-solid fa-teeth-open',
		'fa-solid fa-file-circle-minus',
		'fa-solid fa-tags',
		'fa-solid fa-wine-glass',
		'fa-solid fa-fast-forward fa-forward-fast',
		'fa-solid fa-face-meh-blank fa-meh-blank',
		'fa-solid fa-parking fa-square-parking',
		'fa-solid fa-house-signal',
		'fa-solid fa-bars-progress fa-tasks-alt',
		'fa-solid fa-faucet-drip',
		'fa-solid fa-cart-flatbed fa-dolly-flatbed',
		'fa-solid fa-ban-smoking fa-smoking-ban',
		'fa-solid fa-terminal',
		'fa-solid fa-mobile-button',
		'fa-solid fa-house-medical-flag',
		'fa-solid fa-basket-shopping fa-shopping-basket',
		'fa-solid fa-tape',
		'fa-solid fa-bus-alt fa-bus-simple',
		'fa-solid fa-eye',
		'fa-solid fa-face-sad-cry fa-sad-cry',
		'fa-solid fa-audio-description',
		'fa-solid fa-person-military-to-person',
		'fa-solid fa-file-shield',
		'fa-solid fa-user-slash',
		'fa-solid fa-pen',
		'fa-solid fa-tower-observation',
		'fa-solid fa-file-code',
		'fa-solid fa-signal-5 fa-signal-perfect fa-signal',
		'fa-solid fa-bus',
		'fa-solid fa-heart-circle-xmark',
		'fa-solid fa-home-lg fa-house-chimney',
		'fa-solid fa-window-maximize',
		'fa-solid fa-face-frown fa-frown',
		'fa-solid fa-prescription',
		'fa-solid fa-shop fa-store-alt',
		'fa-solid fa-floppy-disk fa-save',
		'fa-solid fa-vihara',
		'fa-solid fa-balance-scale-left fa-scale-unbalanced',
		'fa-solid fa-sort-asc fa-sort-up',
		'fa-solid fa-comment-dots fa-commenting',
		'fa-solid fa-plant-wilt',
		'fa-solid fa-diamond',
		'fa-solid fa-face-grin-squint fa-grin-squint',
		'fa-solid fa-hand-holding-dollar fa-hand-holding-usd',
		'fa-solid fa-bacterium',
		'fa-solid fa-hand-pointer',
		'fa-solid fa-drum-steelpan',
		'fa-solid fa-hand-scissors',
		'fa-solid fa-hands-praying fa-praying-hands',
		'fa-solid fa-arrow-right-rotate fa-arrow-rotate-forward fa-arrow-rotate-right fa-redo',
		'fa-solid fa-biohazard',
		'fa-solid fa-location-crosshairs fa-location',
		'fa-solid fa-mars-double',
		'fa-solid fa-child-dress',
		'fa-solid fa-users-between-lines',
		'fa-solid fa-lungs-virus',
		'fa-solid fa-face-grin-tears fa-grin-tears',
		'fa-solid fa-phone',
		'fa-solid fa-calendar-times fa-calendar-xmark',
		'fa-solid fa-child-reaching',
		'fa-solid fa-head-side-virus',
		'fa-solid fa-user-cog fa-user-gear',
		'fa-solid fa-arrow-up-1-9 fa-sort-numeric-up',
		'fa-solid fa-door-closed',
		'fa-solid fa-shield-virus',
		'fa-solid fa-dice-six',
		'fa-solid fa-mosquito-net',
		'fa-solid fa-bridge-water',
		'fa-solid fa-person-booth',
		'fa-solid fa-text-width',
		'fa-solid fa-hat-wizard',
		'fa-solid fa-pen-fancy',
		'fa-solid fa-digging fa-person-digging',
		'fa-solid fa-trash',
		'fa-solid fa-gauge-simple-med fa-gauge-simple fa-tachometer-average',
		'fa-solid fa-book-medical',
		'fa-solid fa-poo',
		'fa-solid fa-quote-right-alt fa-quote-right',
		'fa-solid fa-shirt fa-t-shirt fa-tshirt',
		'fa-solid fa-cubes',
		'fa-solid fa-divide',
		'fa-solid fa-tenge-sign fa-tenge',
		'fa-solid fa-headphones',
		'fa-solid fa-hands-holding',
		'fa-solid fa-hands-clapping',
		'fa-solid fa-republican',
		'fa-solid fa-arrow-left',
		'fa-solid fa-person-circle-xmark',
		'fa-solid fa-ruler',
		'fa-solid fa-align-left',
		'fa-solid fa-dice-d6',
		'fa-solid fa-restroom',
		'fa-solid fa-j',
		'fa-solid fa-users-viewfinder',
		'fa-solid fa-file-video',
		'fa-solid fa-external-link-alt fa-up-right-from-square',
		'fa-solid fa-table-cells fa-th',
		'fa-solid fa-file-pdf',
		'fa-solid fa-bible fa-book-bible',
		'fa-solid fa-o',
		'fa-solid fa-medkit fa-suitcase-medical',
		'fa-solid fa-user-secret',
		'fa-solid fa-otter',
		'fa-solid fa-female fa-person-dress',
		'fa-solid fa-comment-dollar',
		'fa-solid fa-briefcase-clock fa-business-time',
		'fa-solid fa-table-cells-large fa-th-large',
		'fa-solid fa-book-tanakh fa-tanakh',
		'fa-solid fa-phone-volume fa-volume-control-phone',
		'fa-solid fa-hat-cowboy-side',
		'fa-solid fa-clipboard-user',
		'fa-solid fa-child',
		'fa-solid fa-lira-sign',
		'fa-solid fa-satellite',
		'fa-solid fa-plane-lock',
		'fa-solid fa-tag',
		'fa-solid fa-comment',
		'fa-solid fa-birthday-cake fa-cake-candles fa-cake',
		'fa-solid fa-envelope',
		'fa-solid fa-angle-double-up fa-angles-up',
		'fa-solid fa-paperclip',
		'fa-solid fa-arrow-right-to-city',
		'fa-solid fa-ribbon',
		'fa-solid fa-lungs',
		'fa-solid fa-arrow-up-9-1 fa-sort-numeric-up-alt',
		'fa-solid fa-litecoin-sign',
		'fa-solid fa-border-none',
		'fa-solid fa-circle-nodes',
		'fa-solid fa-parachute-box',
		'fa-solid fa-indent',
		'fa-solid fa-truck-field-un',
		'fa-solid fa-hourglass-empty fa-hourglass',
		'fa-solid fa-mountain',
		'fa-solid fa-user-doctor fa-user-md',
		'fa-solid fa-circle-info fa-info-circle',
		'fa-solid fa-cloud-meatball',
		'fa-solid fa-camera-alt fa-camera',
		'fa-solid fa-square-virus',
		'fa-solid fa-meteor',
		'fa-solid fa-car-on',
		'fa-solid fa-sleigh',
		'fa-solid fa-arrow-down-1-9 fa-sort-numeric-asc fa-sort-numeric-down',
		'fa-solid fa-hand-holding-droplet fa-hand-holding-water',
		'fa-solid fa-water',
		'fa-solid fa-calendar-check',
		'fa-solid fa-braille',
		'fa-solid fa-prescription-bottle-alt fa-prescription-bottle-medical',
		'fa-solid fa-landmark',
		'fa-solid fa-truck',
		'fa-solid fa-crosshairs',
		'fa-solid fa-person-cane',
		'fa-solid fa-tent',
		'fa-solid fa-vest-patches',
		'fa-solid fa-check-double',
		'fa-solid fa-arrow-down-a-z fa-sort-alpha-asc fa-sort-alpha-down',
		'fa-solid fa-money-bill-wheat',
		'fa-solid fa-cookie',
		'fa-solid fa-arrow-left-rotate fa-arrow-rotate-back fa-arrow-rotate-backward fa-arrow-rotate-left fa-undo',
		'fa-solid fa-hard-drive fa-hdd',
		'fa-solid fa-face-grin-squint-tears fa-grin-squint-tears',
		'fa-solid fa-dumbbell',
		'fa-solid fa-list-alt fa-rectangle-list',
		'fa-solid fa-tarp-droplet',
		'fa-solid fa-house-medical-circle-check',
		'fa-solid fa-person-skiing-nordic fa-skiing-nordic',
		'fa-solid fa-calendar-plus',
		'fa-solid fa-plane-arrival',
		'fa-solid fa-arrow-alt-circle-left fa-circle-left',
		'fa-solid fa-subway fa-train-subway',
		'fa-solid fa-chart-gantt',
		'fa-solid fa-indian-rupee-sign fa-indian-rupee fa-inr',
		'fa-solid fa-crop-alt fa-crop-simple',
		'fa-solid fa-money-bill-1 fa-money-bill-alt',
		'fa-solid fa-left-long fa-long-arrow-alt-left',
		'fa-solid fa-dna',
		'fa-solid fa-virus-slash',
		'fa-solid fa-minus fa-subtract',
		'fa-solid fa-chess',
		'fa-solid fa-arrow-left-long fa-long-arrow-left',
		'fa-solid fa-plug-circle-check',
		'fa-solid fa-street-view',
		'fa-solid fa-franc-sign',
		'fa-solid fa-volume-off',
		'fa-solid fa-american-sign-language-interpreting fa-asl-interpreting fa-hands-american-sign-language-interpreting fa-hands-asl-interpreting',
		'fa-solid fa-cog fa-gear',
		'fa-solid fa-droplet-slash fa-tint-slash',
		'fa-solid fa-mosque',
		'fa-solid fa-mosquito',
		'fa-solid fa-star-of-david',
		'fa-solid fa-person-military-rifle',
		'fa-solid fa-cart-shopping fa-shopping-cart',
		'fa-solid fa-vials',
		'fa-solid fa-plug-circle-plus',
		'fa-solid fa-place-of-worship',
		'fa-solid fa-grip-vertical',
		'fa-solid fa-arrow-turn-up fa-level-up',
		'fa-solid fa-u',
		'fa-solid fa-square-root-alt fa-square-root-variable',
		'fa-solid fa-clock-four fa-clock',
		'fa-solid fa-backward-step fa-step-backward',
		'fa-solid fa-pallet',
		'fa-solid fa-faucet',
		'fa-solid fa-baseball-bat-ball',
		'fa-solid fa-s',
		'fa-solid fa-timeline',
		'fa-solid fa-keyboard',
		'fa-solid fa-caret-down',
		'fa-solid fa-clinic-medical fa-house-chimney-medical',
		'fa-solid fa-temperature-3 fa-temperature-three-quarters fa-thermometer-3 fa-thermometer-three-quarters',
		'fa-solid fa-mobile-android-alt fa-mobile-screen',
		'fa-solid fa-plane-up',
		'fa-solid fa-piggy-bank',
		'fa-solid fa-battery-3 fa-battery-half',
		'fa-solid fa-mountain-city',
		'fa-solid fa-coins',
		'fa-solid fa-khanda',
		'fa-solid fa-sliders-h fa-sliders',
		'fa-solid fa-folder-tree',
		'fa-solid fa-network-wired',
		'fa-solid fa-map-pin',
		'fa-solid fa-hamsa',
		'fa-solid fa-cent-sign',
		'fa-solid fa-flask',
		'fa-solid fa-person-pregnant',
		'fa-solid fa-wand-sparkles',
		'fa-solid fa-ellipsis-v fa-ellipsis-vertical',
		'fa-solid fa-ticket',
		'fa-solid fa-power-off',
		'fa-solid fa-long-arrow-alt-right fa-right-long',
		'fa-solid fa-flag-usa',
		'fa-solid fa-laptop-file',
		'fa-solid fa-teletype fa-tty',
		'fa-solid fa-diagram-next',
		'fa-solid fa-person-rifle',
		'fa-solid fa-house-medical-circle-exclamation',
		'fa-solid fa-closed-captioning',
		'fa-solid fa-hiking fa-person-hiking',
		'fa-solid fa-venus-double',
		'fa-solid fa-images',
		'fa-solid fa-calculator',
		'fa-solid fa-people-pulling',
		'fa-solid fa-n',
		'fa-solid fa-cable-car fa-tram',
		'fa-solid fa-cloud-rain',
		'fa-solid fa-building-circle-xmark',
		'fa-solid fa-ship',
		'fa-solid fa-arrows-down-to-line',
		'fa-solid fa-download',
		'fa-solid fa-face-grin fa-grin',
		'fa-solid fa-backspace fa-delete-left',
		'fa-solid fa-eye-dropper-empty fa-eye-dropper fa-eyedropper',
		'fa-solid fa-file-circle-check',
		'fa-solid fa-forward',
		'fa-solid fa-mobile-android fa-mobile-phone fa-mobile',
		'fa-solid fa-face-meh fa-meh',
		'fa-solid fa-align-center',
		'fa-solid fa-book-dead fa-book-skull',
		'fa-solid fa-drivers-license fa-id-card',
		'fa-solid fa-dedent fa-outdent',
		'fa-solid fa-heart-circle-exclamation',
		'fa-solid fa-home-alt fa-home-lg-alt fa-home fa-house',
		'fa-solid fa-calendar-week',
		'fa-solid fa-laptop-medical',
		'fa-solid fa-b',
		'fa-solid fa-file-medical',
		'fa-solid fa-dice-one',
		'fa-solid fa-kiwi-bird',
		'fa-solid fa-arrow-right-arrow-left fa-exchange',
		'fa-solid fa-redo-alt fa-rotate-forward fa-rotate-right',
		'fa-solid fa-cutlery fa-utensils',
		'fa-solid fa-arrow-up-wide-short fa-sort-amount-up',
		'fa-solid fa-mill-sign',
		'fa-solid fa-bowl-rice',
		'fa-solid fa-skull',
		'fa-solid fa-broadcast-tower fa-tower-broadcast',
		'fa-solid fa-truck-pickup',
		'fa-solid fa-long-arrow-alt-up fa-up-long',
		'fa-solid fa-stop',
		'fa-solid fa-code-merge',
		'fa-solid fa-upload',
		'fa-solid fa-hurricane',
		'fa-solid fa-mound',
		'fa-solid fa-toilet-portable',
		'fa-solid fa-compact-disc',
		'fa-solid fa-file-arrow-down fa-file-download',
		'fa-solid fa-caravan',
		'fa-solid fa-shield-cat',
		'fa-solid fa-bolt fa-zap',
		'fa-solid fa-glass-water',
		'fa-solid fa-oil-well',
		'fa-solid fa-vault',
		'fa-solid fa-mars',
		'fa-solid fa-toilet',
		'fa-solid fa-plane-circle-xmark',
		'fa-solid fa-cny fa-jpy fa-rmb fa-yen-sign fa-yen',
		'fa-solid fa-rouble fa-rub fa-ruble-sign fa-ruble',
		'fa-solid fa-sun',
		'fa-solid fa-guitar',
		'fa-solid fa-face-laugh-wink fa-laugh-wink',
		'fa-solid fa-horse-head',
		'fa-solid fa-bore-hole',
		'fa-solid fa-industry',
		'fa-solid fa-arrow-alt-circle-down fa-circle-down',
		'fa-solid fa-arrows-turn-to-dots',
		'fa-solid fa-florin-sign',
		'fa-solid fa-arrow-down-short-wide fa-sort-amount-desc fa-sort-amount-down-alt',
		'fa-solid fa-less-than',
		'fa-solid fa-angle-down',
		'fa-solid fa-car-tunnel',
		'fa-solid fa-head-side-cough',
		'fa-solid fa-grip-lines',
		'fa-solid fa-thumbs-down',
		'fa-solid fa-user-lock',
		'fa-solid fa-arrow-right-long fa-long-arrow-right',
		'fa-solid fa-anchor-circle-xmark',
		'fa-solid fa-ellipsis-h fa-ellipsis',
		'fa-solid fa-chess-pawn',
		'fa-solid fa-first-aid fa-kit-medical',
		'fa-solid fa-person-through-window',
		'fa-solid fa-toolbox',
		'fa-solid fa-hands-holding-circle',
		'fa-solid fa-bug',
		'fa-solid fa-credit-card-alt fa-credit-card',
		'fa-solid fa-automobile fa-car',
		'fa-solid fa-hand-holding-hand',
		'fa-solid fa-book-open-reader fa-book-reader',
		'fa-solid fa-mountain-sun',
		'fa-solid fa-arrows-left-right-to-line',
		'fa-solid fa-dice-d20',
		'fa-solid fa-truck-droplet',
		'fa-solid fa-file-circle-xmark',
		'fa-solid fa-temperature-arrow-up fa-temperature-up',
		'fa-solid fa-medal',
		'fa-solid fa-bed',
		'fa-solid fa-h-square fa-square-h',
		'fa-solid fa-podcast',
		'fa-solid fa-temperature-4 fa-temperature-full fa-thermometer-4 fa-thermometer-full',
		'fa-solid fa-bell',
		'fa-solid fa-superscript',
		'fa-solid fa-plug-circle-xmark',
		'fa-solid fa-star-of-life',
		'fa-solid fa-phone-slash',
		'fa-solid fa-paint-roller',
		'fa-solid fa-hands-helping fa-handshake-angle',
		'fa-solid fa-location-dot fa-map-marker-alt',
		'fa-solid fa-file',
		'fa-solid fa-greater-than',
		'fa-solid fa-person-swimming fa-swimmer',
		'fa-solid fa-arrow-down',
		'fa-solid fa-droplet fa-tint',
		'fa-solid fa-eraser',
		'fa-solid fa-earth-america fa-earth-americas fa-earth fa-globe-americas',
		'fa-solid fa-person-burst',
		'fa-solid fa-dove',
		'fa-solid fa-battery-0 fa-battery-empty',
		'fa-solid fa-socks',
		'fa-solid fa-inbox',
		'fa-solid fa-section',
		'fa-solid fa-gauge-high fa-tachometer-alt-fast fa-tachometer-alt',
		'fa-solid fa-envelope-open-text',
		'fa-solid fa-hospital-alt fa-hospital-wide fa-hospital',
		'fa-solid fa-wine-bottle',
		'fa-solid fa-chess-rook',
		'fa-solid fa-bars-staggered fa-reorder fa-stream',
		'fa-solid fa-dharmachakra',
		'fa-solid fa-hotdog',
		'fa-solid fa-blind fa-person-walking-with-cane',
		'fa-solid fa-drum',
		'fa-solid fa-ice-cream',
		'fa-solid fa-heart-circle-bolt',
		'fa-solid fa-fax',
		'fa-solid fa-paragraph',
		'fa-solid fa-check-to-slot fa-vote-yea',
		'fa-solid fa-star-half',
		'fa-solid fa-boxes-alt fa-boxes-stacked fa-boxes',
		'fa-solid fa-chain fa-link',
		'fa-solid fa-assistive-listening-systems fa-ear-listen',
		'fa-solid fa-tree-city',
		'fa-solid fa-play',
		'fa-solid fa-font',
		'fa-solid fa-rupiah-sign',
		'fa-solid fa-magnifying-glass fa-search',
		'fa-solid fa-ping-pong-paddle-ball fa-table-tennis-paddle-ball fa-table-tennis',
		'fa-solid fa-diagnoses fa-person-dots-from-line',
		'fa-solid fa-trash-can-arrow-up fa-trash-restore-alt',
		'fa-solid fa-naira-sign',
		'fa-solid fa-cart-arrow-down',
		'fa-solid fa-walkie-talkie',
		'fa-solid fa-file-edit fa-file-pen',
		'fa-solid fa-receipt',
		'fa-solid fa-pen-square fa-pencil-square fa-square-pen',
		'fa-solid fa-suitcase-rolling',
		'fa-solid fa-person-circle-exclamation',
		'fa-solid fa-chevron-down',
		'fa-solid fa-battery-5 fa-battery-full fa-battery',
		'fa-solid fa-skull-crossbones',
		'fa-solid fa-code-compare',
		'fa-solid fa-list-dots fa-list-ul',
		'fa-solid fa-school-lock',
		'fa-solid fa-tower-cell',
		'fa-solid fa-down-long fa-long-arrow-alt-down',
		'fa-solid fa-ranking-star',
		'fa-solid fa-chess-king',
		'fa-solid fa-person-harassing',
		'fa-solid fa-brazilian-real-sign',
		'fa-solid fa-landmark-alt fa-landmark-dome',
		'fa-solid fa-arrow-up',
		'fa-solid fa-television fa-tv-alt fa-tv',
		'fa-solid fa-shrimp',
		'fa-solid fa-list-check fa-tasks',
		'fa-solid fa-jug-detergent',
		'fa-solid fa-circle-user fa-user-circle',
		'fa-solid fa-user-shield',
		'fa-solid fa-wind',
		'fa-solid fa-car-burst fa-car-crash',
		'fa-solid fa-y',
		'fa-solid fa-person-snowboarding fa-snowboarding',
		'fa-solid fa-shipping-fast fa-truck-fast',
		'fa-solid fa-fish',
		'fa-solid fa-user-graduate',
		'fa-solid fa-adjust fa-circle-half-stroke',
		'fa-solid fa-clapperboard',
		'fa-solid fa-circle-radiation fa-radiation-alt',
		'fa-solid fa-baseball-ball fa-baseball',
		'fa-solid fa-jet-fighter-up',
		'fa-solid fa-diagram-project fa-project-diagram',
		'fa-solid fa-copy',
		'fa-solid fa-volume-mute fa-volume-times fa-volume-xmark',
		'fa-solid fa-hand-sparkles',
		'fa-solid fa-grip-horizontal fa-grip',
		'fa-solid fa-share-from-square fa-share-square',
		'fa-solid fa-child-combatant fa-child-rifle',
		'fa-solid fa-gun',
		'fa-solid fa-phone-square fa-square-phone',
		'fa-solid fa-add fa-plus',
		'fa-solid fa-expand',
		'fa-solid fa-computer',
		'fa-solid fa-close fa-multiply fa-remove fa-times fa-xmark',
		'fa-solid fa-arrows-up-down-left-right fa-arrows',
		'fa-solid fa-chalkboard-teacher fa-chalkboard-user',
		'fa-solid fa-peso-sign',
		'fa-solid fa-building-shield',
		'fa-solid fa-baby',
		'fa-solid fa-users-line',
		'fa-solid fa-quote-left-alt fa-quote-left',
		'fa-solid fa-tractor',
		'fa-solid fa-trash-arrow-up fa-trash-restore',
		'fa-solid fa-arrow-down-up-lock',
		'fa-solid fa-lines-leaning',
		'fa-solid fa-ruler-combined',
		'fa-solid fa-copyright',
		'fa-solid fa-equals',
		'fa-solid fa-blender',
		'fa-solid fa-teeth',
		'fa-solid fa-ils fa-shekel-sign fa-shekel fa-sheqel-sign fa-sheqel',
		'fa-solid fa-map',
		'fa-solid fa-rocket',
		'fa-solid fa-photo-film fa-photo-video',
		'fa-solid fa-folder-minus',
		'fa-solid fa-store',
		'fa-solid fa-arrow-trend-up',
		'fa-solid fa-plug-circle-minus',
		'fa-solid fa-sign-hanging fa-sign',
		'fa-solid fa-bezier-curve',
		'fa-solid fa-bell-slash',
		'fa-solid fa-tablet-android fa-tablet',
		'fa-solid fa-school-flag',
		'fa-solid fa-fill',
		'fa-solid fa-angle-up',
		'fa-solid fa-drumstick-bite',
		'fa-solid fa-holly-berry',
		'fa-solid fa-chevron-left',
		'fa-solid fa-bacteria',
		'fa-solid fa-hand-lizard',
		'fa-solid fa-notdef',
		'fa-solid fa-disease',
		'fa-solid fa-briefcase-medical',
		'fa-solid fa-genderless',
		'fa-solid fa-chevron-right',
		'fa-solid fa-retweet',
		'fa-solid fa-car-alt fa-car-rear',
		'fa-solid fa-pump-soap',
		'fa-solid fa-video-slash',
		'fa-solid fa-battery-2 fa-battery-quarter',
		'fa-solid fa-radio',
		'fa-solid fa-baby-carriage fa-carriage-baby',
		'fa-solid fa-traffic-light',
		'fa-solid fa-thermometer',
		'fa-solid fa-vr-cardboard',
		'fa-solid fa-hand-middle-finger',
		'fa-solid fa-percent fa-percentage',
		'fa-solid fa-truck-moving',
		'fa-solid fa-glass-water-droplet',
		'fa-solid fa-display',
		'fa-solid fa-face-smile fa-smile',
		'fa-solid fa-thumb-tack fa-thumbtack',
		'fa-solid fa-trophy',
		'fa-solid fa-person-praying fa-pray',
		'fa-solid fa-hammer',
		'fa-solid fa-hand-peace',
		'fa-solid fa-rotate fa-sync-alt',
		'fa-solid fa-spinner',
		'fa-solid fa-robot',
		'fa-solid fa-peace',
		'fa-solid fa-cogs fa-gears',
		'fa-solid fa-warehouse',
		'fa-solid fa-arrow-up-right-dots',
		'fa-solid fa-splotch',
		'fa-solid fa-face-grin-hearts fa-grin-hearts',
		'fa-solid fa-dice-four',
		'fa-solid fa-sim-card',
		'fa-solid fa-transgender-alt fa-transgender',
		'fa-solid fa-mercury',
		'fa-solid fa-arrow-turn-down fa-level-down',
		'fa-solid fa-person-falling-burst',
		'fa-solid fa-award',
		'fa-solid fa-ticket-alt fa-ticket-simple',
		'fa-solid fa-building',
		'fa-solid fa-angle-double-left fa-angles-left',
		'fa-solid fa-qrcode',
		'fa-solid fa-clock-rotate-left fa-history',
		'fa-solid fa-face-grin-beam-sweat fa-grin-beam-sweat',
		'fa-solid fa-arrow-right-from-file fa-file-export',
		'fa-solid fa-shield-blank fa-shield',
		'fa-solid fa-arrow-up-short-wide fa-sort-amount-up-alt',
		'fa-solid fa-house-medical',
		'fa-solid fa-golf-ball-tee fa-golf-ball',
		'fa-solid fa-chevron-circle-left fa-circle-chevron-left',
		'fa-solid fa-house-chimney-window',
		'fa-solid fa-pen-nib',
		'fa-solid fa-tent-arrow-turn-left',
		'fa-solid fa-tents',
		'fa-solid fa-magic fa-wand-magic',
		'fa-solid fa-dog',
		'fa-solid fa-carrot',
		'fa-solid fa-moon',
		'fa-solid fa-wine-glass-alt fa-wine-glass-empty',
		'fa-solid fa-cheese',
		'fa-solid fa-yin-yang',
		'fa-solid fa-music',
		'fa-solid fa-code-commit',
		'fa-solid fa-temperature-low',
		'fa-solid fa-biking fa-person-biking',
		'fa-solid fa-broom',
		'fa-solid fa-shield-heart',
		'fa-solid fa-gopuram',
		'fa-solid fa-earth-oceania fa-globe-oceania',
		'fa-solid fa-square-xmark fa-times-square fa-xmark-square',
		'fa-solid fa-hashtag',
		'fa-solid fa-expand-alt fa-up-right-and-down-left-from-center',
		'fa-solid fa-oil-can',
		'fa-solid fa-t',
		'fa-solid fa-hippo',
		'fa-solid fa-chart-column',
		'fa-solid fa-infinity',
		'fa-solid fa-vial-circle-check',
		'fa-solid fa-person-arrow-down-to-line',
		'fa-solid fa-voicemail',
		'fa-solid fa-fan',
		'fa-solid fa-person-walking-luggage',
		'fa-solid fa-arrows-alt-v fa-up-down',
		'fa-solid fa-cloud-moon-rain',
		'fa-solid fa-calendar',
		'fa-solid fa-trailer',
		'fa-solid fa-bahai fa-haykal',
		'fa-solid fa-sd-card',
		'fa-solid fa-dragon',
		'fa-solid fa-shoe-prints',
		'fa-solid fa-circle-plus fa-plus-circle',
		'fa-solid fa-face-grin-tongue-wink fa-grin-tongue-wink',
		'fa-solid fa-hand-holding',
		'fa-solid fa-plug-circle-exclamation',
		'fa-solid fa-chain-broken fa-chain-slash fa-link-slash fa-unlink',
		'fa-solid fa-clone',
		'fa-solid fa-person-walking-arrow-loop-left',
		'fa-solid fa-arrow-up-z-a fa-sort-alpha-up-alt',
		'fa-solid fa-fire-alt fa-fire-flame-curved',
		'fa-solid fa-tornado',
		'fa-solid fa-file-circle-plus',
		'fa-solid fa-book-quran fa-quran',
		'fa-solid fa-anchor',
		'fa-solid fa-border-all',
		'fa-solid fa-angry fa-face-angry',
		'fa-solid fa-cookie-bite',
		'fa-solid fa-arrow-trend-down',
		'fa-solid fa-feed fa-rss',
		'fa-solid fa-draw-polygon',
		'fa-solid fa-balance-scale fa-scale-balanced',
		'fa-solid fa-gauge-simple-high fa-tachometer-fast fa-tachometer',
		'fa-solid fa-shower',
		'fa-solid fa-desktop-alt fa-desktop',
		'fa-solid fa-m',
		'fa-solid fa-table-list fa-th-list',
		'fa-solid fa-comment-sms fa-sms',
		'fa-solid fa-book',
		'fa-solid fa-user-plus',
		'fa-solid fa-check',
		'fa-solid fa-battery-4 fa-battery-three-quarters',
		'fa-solid fa-house-circle-check',
		'fa-solid fa-angle-left',
		'fa-solid fa-diagram-successor',
		'fa-solid fa-truck-arrow-right',
		'fa-solid fa-arrows-split-up-and-left',
		'fa-solid fa-fist-raised fa-hand-fist',
		'fa-solid fa-cloud-moon',
		'fa-solid fa-briefcase',
		'fa-solid fa-person-falling',
		'fa-solid fa-image-portrait fa-portrait',
		'fa-solid fa-user-tag',
		'fa-solid fa-rug',
		'fa-solid fa-earth-europe fa-globe-europe',
		'fa-solid fa-cart-flatbed-suitcase fa-luggage-cart',
		'fa-solid fa-rectangle-times fa-rectangle-xmark fa-times-rectangle fa-window-close',
		'fa-solid fa-baht-sign',
		'fa-solid fa-book-open',
		'fa-solid fa-book-journal-whills fa-journal-whills',
		'fa-solid fa-handcuffs',
		'fa-solid fa-exclamation-triangle fa-triangle-exclamation fa-warning',
		'fa-solid fa-database',
		'fa-solid fa-arrow-turn-right fa-mail-forward fa-share',
		'fa-solid fa-bottle-droplet',
		'fa-solid fa-mask-face',
		'fa-solid fa-hill-rockslide',
		'fa-solid fa-exchange-alt fa-right-left',
		'fa-solid fa-paper-plane',
		'fa-solid fa-road-circle-exclamation',
		'fa-solid fa-dungeon',
		'fa-solid fa-align-right',
		'fa-solid fa-money-bill-1-wave fa-money-bill-wave-alt',
		'fa-solid fa-life-ring',
		'fa-solid fa-hands fa-sign-language fa-signing',
		'fa-solid fa-calendar-day',
		'fa-solid fa-ladder-water fa-swimming-pool fa-water-ladder',
		'fa-solid fa-arrows-up-down fa-arrows-v',
		'fa-solid fa-face-grimace fa-grimace',
		'fa-solid fa-wheelchair-alt fa-wheelchair-move',
		'fa-solid fa-level-down-alt fa-turn-down',
		'fa-solid fa-person-walking-arrow-right',
		'fa-solid fa-envelope-square fa-square-envelope',
		'fa-solid fa-dice',
		'fa-solid fa-bowling-ball',
		'fa-solid fa-brain',
		'fa-solid fa-band-aid fa-bandage',
		'fa-solid fa-calendar-minus',
		'fa-solid fa-circle-xmark fa-times-circle fa-xmark-circle',
		'fa-solid fa-gifts',
		'fa-solid fa-hotel',
		'fa-solid fa-earth-asia fa-globe-asia',
		'fa-solid fa-id-card-alt fa-id-card-clip',
		'fa-solid fa-magnifying-glass-plus fa-search-plus',
		'fa-solid fa-thumbs-up',
		'fa-solid fa-user-clock',
		'fa-solid fa-allergies fa-hand-dots',
		'fa-solid fa-file-invoice',
		'fa-solid fa-window-minimize',
		'fa-solid fa-coffee fa-mug-saucer',
		'fa-solid fa-brush',
		'fa-solid fa-mask',
		'fa-solid fa-magnifying-glass-minus fa-search-minus',
		'fa-solid fa-ruler-vertical',
		'fa-solid fa-user-alt fa-user-large',
		'fa-solid fa-train-tram',
		'fa-solid fa-user-nurse',
		'fa-solid fa-syringe',
		'fa-solid fa-cloud-sun',
		'fa-solid fa-stopwatch-20',
		'fa-solid fa-square-full',
		'fa-solid fa-magnet',
		'fa-solid fa-jar',
		'fa-solid fa-note-sticky fa-sticky-note',
		'fa-solid fa-bug-slash',
		'fa-solid fa-arrow-up-from-water-pump',
		'fa-solid fa-bone',
		'fa-solid fa-user-injured',
		'fa-solid fa-face-sad-tear fa-sad-tear',
		'fa-solid fa-plane',
		'fa-solid fa-tent-arrows-down',
		'fa-solid fa-exclamation',
		'fa-solid fa-arrows-spin',
		'fa-solid fa-print',
		'fa-solid fa-try fa-turkish-lira-sign fa-turkish-lira',
		'fa-solid fa-dollar-sign fa-dollar fa-usd',
		'fa-solid fa-x',
		'fa-solid fa-magnifying-glass-dollar fa-search-dollar',
		'fa-solid fa-users-cog fa-users-gear',
		'fa-solid fa-person-military-pointing',
		'fa-solid fa-bank fa-building-columns fa-institution fa-museum fa-university',
		'fa-solid fa-umbrella',
		'fa-solid fa-trowel',
		'fa-solid fa-d',
		'fa-solid fa-stapler',
		'fa-solid fa-masks-theater fa-theater-masks',
		'fa-solid fa-kip-sign',
		'fa-solid fa-hand-point-left',
		'fa-solid fa-handshake-alt fa-handshake-simple',
		'fa-solid fa-fighter-jet fa-jet-fighter',
		'fa-solid fa-share-alt-square fa-square-share-nodes',
		'fa-solid fa-barcode',
		'fa-solid fa-plus-minus',
		'fa-solid fa-video-camera fa-video',
		'fa-solid fa-graduation-cap fa-mortar-board',
		'fa-solid fa-hand-holding-medical',
		'fa-solid fa-person-circle-check',
		'fa-solid fa-level-up-alt fa-turn-up',
		'fa-brands fa-monero',
		'fa-brands fa-hooli',
		'fa-brands fa-yelp',
		'fa-brands fa-cc-visa',
		'fa-brands fa-lastfm',
		'fa-brands fa-shopware',
		'fa-brands fa-creative-commons-nc',
		'fa-brands fa-aws',
		'fa-brands fa-redhat',
		'fa-brands fa-yoast',
		'fa-brands fa-cloudflare',
		'fa-brands fa-ups',
		'fa-brands fa-wpexplorer',
		'fa-brands fa-dyalog',
		'fa-brands fa-bity',
		'fa-brands fa-stackpath',
		'fa-brands fa-buysellads',
		'fa-brands fa-first-order',
		'fa-brands fa-modx',
		'fa-brands fa-guilded',
		'fa-brands fa-vnv',
		'fa-brands fa-js-square fa-square-js',
		'fa-brands fa-microsoft',
		'fa-brands fa-qq',
		'fa-brands fa-orcid',
		'fa-brands fa-java',
		'fa-brands fa-invision',
		'fa-brands fa-creative-commons-pd-alt',
		'fa-brands fa-centercode',
		'fa-brands fa-glide-g',
		'fa-brands fa-drupal',
		'fa-brands fa-hire-a-helper',
		'fa-brands fa-creative-commons-by',
		'fa-brands fa-unity',
		'fa-brands fa-whmcs',
		'fa-brands fa-rocketchat',
		'fa-brands fa-vk',
		'fa-brands fa-untappd',
		'fa-brands fa-mailchimp',
		'fa-brands fa-css3-alt',
		'fa-brands fa-reddit-square fa-square-reddit',
		'fa-brands fa-vimeo-v',
		'fa-brands fa-contao',
		'fa-brands fa-square-font-awesome',
		'fa-brands fa-deskpro',
		'fa-brands fa-sistrix',
		'fa-brands fa-instagram-square fa-square-instagram',
		'fa-brands fa-battle-net',
		'fa-brands fa-the-red-yeti',
		'fa-brands fa-hacker-news-square fa-square-hacker-news',
		'fa-brands fa-edge',
		'fa-brands fa-threads',
		'fa-brands fa-napster',
		'fa-brands fa-snapchat-square fa-square-snapchat',
		'fa-brands fa-google-plus-g',
		'fa-brands fa-artstation',
		'fa-brands fa-markdown',
		'fa-brands fa-sourcetree',
		'fa-brands fa-google-plus',
		'fa-brands fa-diaspora',
		'fa-brands fa-foursquare',
		'fa-brands fa-stack-overflow',
		'fa-brands fa-github-alt',
		'fa-brands fa-phoenix-squadron',
		'fa-brands fa-pagelines',
		'fa-brands fa-algolia',
		'fa-brands fa-red-river',
		'fa-brands fa-creative-commons-sa',
		'fa-brands fa-safari',
		'fa-brands fa-google',
		'fa-brands fa-font-awesome-alt fa-square-font-awesome-stroke',
		'fa-brands fa-atlassian',
		'fa-brands fa-linkedin-in',
		'fa-brands fa-digital-ocean',
		'fa-brands fa-nimblr',
		'fa-brands fa-chromecast',
		'fa-brands fa-evernote',
		'fa-brands fa-hacker-news',
		'fa-brands fa-creative-commons-sampling',
		'fa-brands fa-adversal',
		'fa-brands fa-creative-commons',
		'fa-brands fa-watchman-monitoring',
		'fa-brands fa-fonticons',
		'fa-brands fa-weixin',
		'fa-brands fa-shirtsinbulk',
		'fa-brands fa-codepen',
		'fa-brands fa-git-alt',
		'fa-brands fa-lyft',
		'fa-brands fa-rev',
		'fa-brands fa-windows',
		'fa-brands fa-wizards-of-the-coast',
		'fa-brands fa-square-viadeo fa-viadeo-square',
		'fa-brands fa-meetup',
		'fa-brands fa-centos',
		'fa-brands fa-adn',
		'fa-brands fa-cloudsmith',
		'fa-brands fa-pied-piper-alt',
		'fa-brands fa-dribbble-square fa-square-dribbble',
		'fa-brands fa-codiepie',
		'fa-brands fa-node',
		'fa-brands fa-mix',
		'fa-brands fa-steam',
		'fa-brands fa-cc-apple-pay',
		'fa-brands fa-scribd',
		'fa-brands fa-debian',
		'fa-brands fa-openid',
		'fa-brands fa-instalod',
		'fa-brands fa-expeditedssl',
		'fa-brands fa-sellcast',
		'fa-brands fa-square-twitter fa-twitter-square',
		'fa-brands fa-r-project',
		'fa-brands fa-delicious',
		'fa-brands fa-freebsd',
		'fa-brands fa-vuejs',
		'fa-brands fa-accusoft',
		'fa-brands fa-ioxhost',
		'fa-brands fa-fonticons-fi',
		'fa-brands fa-app-store',
		'fa-brands fa-cc-mastercard',
		'fa-brands fa-itunes-note',
		'fa-brands fa-golang',
		'fa-brands fa-kickstarter',
		'fa-brands fa-grav',
		'fa-brands fa-weibo',
		'fa-brands fa-uncharted',
		'fa-brands fa-firstdraft',
		'fa-brands fa-square-youtube fa-youtube-square',
		'fa-brands fa-wikipedia-w',
		'fa-brands fa-rendact fa-wpressr',
		'fa-brands fa-angellist',
		'fa-brands fa-galactic-republic',
		'fa-brands fa-nfc-directional',
		'fa-brands fa-skype',
		'fa-brands fa-joget',
		'fa-brands fa-fedora',
		'fa-brands fa-stripe-s',
		'fa-brands fa-meta',
		'fa-brands fa-laravel',
		'fa-brands fa-hotjar',
		'fa-brands fa-bluetooth-b',
		'fa-brands fa-sticker-mule',
		'fa-brands fa-creative-commons-zero',
		'fa-brands fa-hips',
		'fa-brands fa-behance',
		'fa-brands fa-reddit',
		'fa-brands fa-discord',
		'fa-brands fa-chrome',
		'fa-brands fa-app-store-ios',
		'fa-brands fa-cc-discover',
		'fa-brands fa-wpbeginner',
		'fa-brands fa-confluence',
		'fa-brands fa-mdb',
		'fa-brands fa-dochub',
		'fa-brands fa-accessible-icon',
		'fa-brands fa-ebay',
		'fa-brands fa-amazon',
		'fa-brands fa-unsplash',
		'fa-brands fa-yarn',
		'fa-brands fa-square-steam fa-steam-square',
		'fa-brands fa-500px',
		'fa-brands fa-square-vimeo fa-vimeo-square',
		'fa-brands fa-asymmetrik',
		'fa-brands fa-font-awesome-flag fa-font-awesome-logo-full fa-font-awesome',
		'fa-brands fa-gratipay',
		'fa-brands fa-apple',
		'fa-brands fa-hive',
		'fa-brands fa-gitkraken',
		'fa-brands fa-keybase',
		'fa-brands fa-apple-pay',
		'fa-brands fa-padlet',
		'fa-brands fa-amazon-pay',
		'fa-brands fa-github-square fa-square-github',
		'fa-brands fa-stumbleupon',
		'fa-brands fa-fedex',
		'fa-brands fa-phoenix-framework',
		'fa-brands fa-shopify',
		'fa-brands fa-neos',
		'fa-brands fa-square-threads',
		'fa-brands fa-hackerrank',
		'fa-brands fa-researchgate',
		'fa-brands fa-swift',
		'fa-brands fa-angular',
		'fa-brands fa-speakap',
		'fa-brands fa-angrycreative',
		'fa-brands fa-y-combinator',
		'fa-brands fa-empire',
		'fa-brands fa-envira',
		'fa-brands fa-gitlab-square fa-square-gitlab',
		'fa-brands fa-studiovinari',
		'fa-brands fa-pied-piper',
		'fa-brands fa-wordpress',
		'fa-brands fa-product-hunt',
		'fa-brands fa-firefox',
		'fa-brands fa-linode',
		'fa-brands fa-goodreads',
		'fa-brands fa-odnoklassniki-square fa-square-odnoklassniki',
		'fa-brands fa-jsfiddle',
		'fa-brands fa-sith',
		'fa-brands fa-themeisle',
		'fa-brands fa-page4',
		'fa-brands fa-hashnode',
		'fa-brands fa-react',
		'fa-brands fa-cc-paypal',
		'fa-brands fa-squarespace',
		'fa-brands fa-cc-stripe',
		'fa-brands fa-creative-commons-share',
		'fa-brands fa-bitcoin',
		'fa-brands fa-keycdn',
		'fa-brands fa-opera',
		'fa-brands fa-itch-io',
		'fa-brands fa-umbraco',
		'fa-brands fa-galactic-senate',
		'fa-brands fa-ubuntu',
		'fa-brands fa-draft2digital',
		'fa-brands fa-stripe',
		'fa-brands fa-houzz',
		'fa-brands fa-gg',
		'fa-brands fa-dhl',
		'fa-brands fa-pinterest-square fa-square-pinterest',
		'fa-brands fa-xing',
		'fa-brands fa-blackberry',
		'fa-brands fa-creative-commons-pd',
		'fa-brands fa-playstation',
		'fa-brands fa-quinscape',
		'fa-brands fa-less',
		'fa-brands fa-blogger-b',
		'fa-brands fa-opencart',
		'fa-brands fa-vine',
		'fa-brands fa-paypal',
		'fa-brands fa-gitlab',
		'fa-brands fa-typo3',
		'fa-brands fa-reddit-alien',
		'fa-brands fa-yahoo',
		'fa-brands fa-dailymotion',
		'fa-brands fa-affiliatetheme',
		'fa-brands fa-pied-piper-pp',
		'fa-brands fa-bootstrap',
		'fa-brands fa-odnoklassniki',
		'fa-brands fa-nfc-symbol',
		'fa-brands fa-ethereum',
		'fa-brands fa-speaker-deck',
		'fa-brands fa-creative-commons-nc-eu',
		'fa-brands fa-patreon',
		'fa-brands fa-avianex',
		'fa-brands fa-ello',
		'fa-brands fa-gofore',
		'fa-brands fa-bimobject',
		'fa-brands fa-facebook-f',
		'fa-brands fa-google-plus-square fa-square-google-plus',
		'fa-brands fa-mandalorian',
		'fa-brands fa-first-order-alt',
		'fa-brands fa-osi',
		'fa-brands fa-google-wallet',
		'fa-brands fa-d-and-d-beyond',
		'fa-brands fa-periscope',
		'fa-brands fa-fulcrum',
		'fa-brands fa-cloudscale',
		'fa-brands fa-forumbee',
		'fa-brands fa-mizuni',
		'fa-brands fa-schlix',
		'fa-brands fa-square-xing fa-xing-square',
		'fa-brands fa-bandcamp',
		'fa-brands fa-wpforms',
		'fa-brands fa-cloudversify',
		'fa-brands fa-usps',
		'fa-brands fa-megaport',
		'fa-brands fa-magento',
		'fa-brands fa-spotify',
		'fa-brands fa-optin-monster',
		'fa-brands fa-fly',
		'fa-brands fa-aviato',
		'fa-brands fa-itunes',
		'fa-brands fa-cuttlefish',
		'fa-brands fa-blogger',
		'fa-brands fa-flickr',
		'fa-brands fa-viber',
		'fa-brands fa-soundcloud',
		'fa-brands fa-digg',
		'fa-brands fa-tencent-weibo',
		'fa-brands fa-symfony',
		'fa-brands fa-maxcdn',
		'fa-brands fa-etsy',
		'fa-brands fa-facebook-messenger',
		'fa-brands fa-audible',
		'fa-brands fa-think-peaks',
		'fa-brands fa-bilibili',
		'fa-brands fa-erlang',
		'fa-brands fa-x-twitter',
		'fa-brands fa-cotton-bureau',
		'fa-brands fa-dashcube',
		'fa-brands fa-42-group fa-innosoft',
		'fa-brands fa-stack-exchange',
		'fa-brands fa-elementor',
		'fa-brands fa-pied-piper-square fa-square-pied-piper',
		'fa-brands fa-creative-commons-nd',
		'fa-brands fa-palfed',
		'fa-brands fa-superpowers',
		'fa-brands fa-resolving',
		'fa-brands fa-xbox',
		'fa-brands fa-searchengin',
		'fa-brands fa-tiktok',
		'fa-brands fa-facebook-square fa-square-facebook',
		'fa-brands fa-renren',
		'fa-brands fa-linux',
		'fa-brands fa-glide',
		'fa-brands fa-linkedin',
		'fa-brands fa-hubspot',
		'fa-brands fa-deploydog',
		'fa-brands fa-twitch',
		'fa-brands fa-ravelry',
		'fa-brands fa-mixer',
		'fa-brands fa-lastfm-square fa-square-lastfm',
		'fa-brands fa-vimeo',
		'fa-brands fa-mendeley',
		'fa-brands fa-uniregistry',
		'fa-brands fa-figma',
		'fa-brands fa-creative-commons-remix',
		'fa-brands fa-cc-amazon-pay',
		'fa-brands fa-dropbox',
		'fa-brands fa-instagram',
		'fa-brands fa-cmplid',
		'fa-brands fa-facebook',
		'fa-brands fa-gripfire',
		'fa-brands fa-jedi-order',
		'fa-brands fa-uikit',
		'fa-brands fa-fort-awesome-alt',
		'fa-brands fa-phabricator',
		'fa-brands fa-ussunnah',
		'fa-brands fa-earlybirds',
		'fa-brands fa-trade-federation',
		'fa-brands fa-autoprefixer',
		'fa-brands fa-whatsapp',
		'fa-brands fa-slideshare',
		'fa-brands fa-google-play',
		'fa-brands fa-viadeo',
		'fa-brands fa-line',
		'fa-brands fa-google-drive',
		'fa-brands fa-servicestack',
		'fa-brands fa-simplybuilt',
		'fa-brands fa-bitbucket',
		'fa-brands fa-imdb',
		'fa-brands fa-deezer',
		'fa-brands fa-raspberry-pi',
		'fa-brands fa-jira',
		'fa-brands fa-docker',
		'fa-brands fa-screenpal',
		'fa-brands fa-bluetooth',
		'fa-brands fa-gitter',
		'fa-brands fa-d-and-d',
		'fa-brands fa-microblog',
		'fa-brands fa-cc-diners-club',
		'fa-brands fa-gg-circle',
		'fa-brands fa-pied-piper-hat',
		'fa-brands fa-kickstarter-k',
		'fa-brands fa-yandex',
		'fa-brands fa-readme',
		'fa-brands fa-html5',
		'fa-brands fa-sellsy',
		'fa-brands fa-sass',
		'fa-brands fa-wirsindhandwerk fa-wsh',
		'fa-brands fa-buromobelexperte',
		'fa-brands fa-salesforce',
		'fa-brands fa-octopus-deploy',
		'fa-brands fa-medapps',
		'fa-brands fa-ns8',
		'fa-brands fa-pinterest-p',
		'fa-brands fa-apper',
		'fa-brands fa-fort-awesome',
		'fa-brands fa-waze',
		'fa-brands fa-cc-jcb',
		'fa-brands fa-snapchat-ghost fa-snapchat',
		'fa-brands fa-fantasy-flight-games',
		'fa-brands fa-rust',
		'fa-brands fa-wix',
		'fa-brands fa-behance-square fa-square-behance',
		'fa-brands fa-supple',
		'fa-brands fa-rebel',
		'fa-brands fa-css3',
		'fa-brands fa-staylinked',
		'fa-brands fa-kaggle',
		'fa-brands fa-space-awesome',
		'fa-brands fa-deviantart',
		'fa-brands fa-cpanel',
		'fa-brands fa-goodreads-g',
		'fa-brands fa-git-square fa-square-git',
		'fa-brands fa-square-tumblr fa-tumblr-square',
		'fa-brands fa-trello',
		'fa-brands fa-creative-commons-nc-jp',
		'fa-brands fa-get-pocket',
		'fa-brands fa-perbyte',
		'fa-brands fa-grunt',
		'fa-brands fa-weebly',
		'fa-brands fa-connectdevelop',
		'fa-brands fa-leanpub',
		'fa-brands fa-black-tie',
		'fa-brands fa-themeco',
		'fa-brands fa-python',
		'fa-brands fa-android',
		'fa-brands fa-bots',
		'fa-brands fa-free-code-camp',
		'fa-brands fa-hornbill',
		'fa-brands fa-js',
		'fa-brands fa-ideal',
		'fa-brands fa-git',
		'fa-brands fa-dev',
		'fa-brands fa-sketch',
		'fa-brands fa-yandex-international',
		'fa-brands fa-cc-amex',
		'fa-brands fa-uber',
		'fa-brands fa-github',
		'fa-brands fa-php',
		'fa-brands fa-alipay',
		'fa-brands fa-youtube',
		'fa-brands fa-skyatlas',
		'fa-brands fa-firefox-browser',
		'fa-brands fa-replyd',
		'fa-brands fa-suse',
		'fa-brands fa-jenkins',
		'fa-brands fa-twitter',
		'fa-brands fa-rockrms',
		'fa-brands fa-pinterest',
		'fa-brands fa-buffer',
		'fa-brands fa-npm',
		'fa-brands fa-yammer',
		'fa-brands fa-btc',
		'fa-brands fa-dribbble',
		'fa-brands fa-stumbleupon-circle',
		'fa-brands fa-internet-explorer',
		'fa-brands fa-stubber',
		'fa-brands fa-telegram-plane fa-telegram',
		'fa-brands fa-old-republic',
		'fa-brands fa-odysee',
		'fa-brands fa-square-whatsapp fa-whatsapp-square',
		'fa-brands fa-node-js',
		'fa-brands fa-edge-legacy',
		'fa-brands fa-slack-hash fa-slack',
		'fa-brands fa-medrt',
		'fa-brands fa-usb',
		'fa-brands fa-tumblr',
		'fa-brands fa-vaadin',
		'fa-brands fa-quora',
		'fa-brands fa-square-x-twitter',
		'fa-brands fa-reacteurope',
		'fa-brands fa-medium-m fa-medium',
		'fa-brands fa-amilia',
		'fa-brands fa-mixcloud',
		'fa-brands fa-flipboard',
		'fa-brands fa-viacoin',
		'fa-brands fa-critical-role',
		'fa-brands fa-sitrox',
		'fa-brands fa-discourse',
		'fa-brands fa-joomla',
		'fa-brands fa-mastodon',
		'fa-brands fa-airbnb',
		'fa-brands fa-wolf-pack-battalion',
		'fa-brands fa-buy-n-large',
		'fa-brands fa-gulp',
		'fa-brands fa-creative-commons-sampling-plus',
		'fa-brands fa-strava',
		'fa-brands fa-ember',
		'fa-brands fa-canadian-maple-leaf',
		'fa-brands fa-teamspeak',
		'fa-brands fa-pushed',
		'fa-brands fa-wordpress-simple',
		'fa-brands fa-nutritionix',
		'fa-brands fa-wodu',
		'fa-brands fa-google-pay',
		'fa-brands fa-intercom',
		'fa-brands fa-zhihu',
		'fa-brands fa-korvue',
		'fa-brands fa-pix',
		'fa-brands fa-steam-symbol',
	);

	return $icons;
}