<?php
// don't load directly
defined( 'ABSPATH' ) || exit;

TF_Metabox::metabox( 'tf_hotels', array(
	'title'     => 'Hotel Settings',
	'post_type' => 'tf_hotel',
	'sections'  => array(
		'section_2' => array(
			'title'  => 'Section 1',
			'icon'   => 'ri-home-2-line',
			'fields' => array(
				array(
					'id' => 'tf-repeater',
					'type' => 'repeater',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'fields' => array(
						array(
							'id' => 'tf-text2',
							'type' => 'text',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'placeholder' => 'Enter your placeholder',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
							'default' => 'Enter your default value',
						),
						array(
							'id' => 'tf-textarea2',
							'type' => 'textarea',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'placeholder' => 'Enter your placeholder',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
							'default' => 'Enter your default value',
						),
						array(
							'id' => 'tf-select3',
							'type' => 'select',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'placeholder' => 'Enter your placeholder',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
							'options' => array(
								'option-1' => 'Option 1',
								'option-2' => 'Option 2',
							 ),
						),
						array(
							'id' => 'tf-checkbox',
							'type' => 'checkbox',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'placeholder' => 'Enter your placeholder',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
							'options' => array(
								'option-1' => 'Option 1',
								'option-2' => 'Option 2',
							 ),
							'default' => 'option-1',
							'inline' => true,
						),
						array(
							'id' => 'tf-radio',
							'type' => 'radio',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'placeholder' => 'Enter your placeholder',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
							'options' => array(
								'option-1' => 'Option 1',
								'option-2' => 'Option 2',
							 ),
							'default' => 'option-1',
							'inline' => true,
						),
						array(
							'id' => 'tf-switch',
							'type' => 'switch',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
							'label_on' => 'On',
							'label_off' => 'Off',
							'width' => 100,
							'default' => true,
						), 
						array(
							'id' => 'tf-icon',
							'type' => 'icon',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
							'default' => 'fa fa-home',
						),
						array(
							'id' => 'tf-image',
							'type' => 'image',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
						),
						array(
							'id' => 'tf-editor',
							'type' => 'editor',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
						),
						array(
							'id' => 'tf-map',
							'type' => 'map',
							'label' => 'Enter your label',
							'subtitle' => 'Enter your subtitle',
							'description' => 'Enter your description',
							'class' => 'tf-field-class',
						)

					 ),
				),
				array(
					'id' => 'tf-tab',
					'type' => 'tab',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'tabs' => array(
						array(
							'id' => 'tab-1',
							'title' => 'Tab 1',
							'icon' => 'fa fa-heart',
							'fields' => array(
								array(
									'id' => 'tab-text',
									'label' => 'Tab Text Field',
									'type' => 'text',
									'subtitle' => 'Enter your subtitle',
									'placeholder' => 'Enter your placeholder',
									'description' => 'Enter your description',
								 ),
							 ),
						 ),
						array(
							'id' => 'tab-2',
							'title' => 'tab 2',
							'icon' => 'fa fa-gear',
							'fields' => array(
								array(
									'id' => 'tab-text2',
									'label' => 'Tab Text Field 2',
									'type' => 'text',
									'subtitle' => 'Enter your subtitle',
									'placeholder' => 'Enter your placeholder',
									'description' => 'Enter your description',
								 ),
							 ),
						 ),
					 ),
				),
				array(
					'id' => 'tf-text',
					'type' => 'text',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'default' => 'Enter your default value',
				),
				array(
					'id' => 'tf-textarea',
					'type' => 'textarea',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'default' => 'Enter your default value',
				),
				array(
					'id' => 'tf-select',
					'type' => 'select',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'options' => array(
						'option-1' => 'Option 1',
						'option-2' => 'Option 2',
					 ),
				),
				array(
					'id' => 'tf-checkbox',
					'type' => 'checkbox',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'options' => array(
						'option-1' => 'Option 1',
						'option-2' => 'Option 2',
					 ),
					'default' => 'option-1',
					'inline' => true,
				),
				array(
					'id' => 'tf-radio',
					'type' => 'radio',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'options' => array(
						'option-1' => 'Option 1',
						'option-2' => 'Option 2',
					 ),
					'default' => 'option-1',
					'inline' => true,
				),
				array(
					'id' => 'tf-switch',
					'type' => 'switch',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'label_on' => 'On',
					'label_off' => 'Off',
					'width' => 100,
					'default' => true,
				),
				array(
					'id' => 'tf-date',
					'type' => 'date',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'format' => 'Y/m/d',
					'range' => true,
					'label_from' => 'Start Date',
					'label_to' => 'End Date',
					'multiple' => true,
				),
				array(
					'id' => 'tf-time',
					'type' => 'time',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'format' => 'h:i K',
				),
				array(
					'id' => 'tf-select2',
					'type' => 'select2',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'placeholder' => 'Enter your placeholder',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'options' => array(
						'option-1' => 'Option 1',
						'option-2' => 'Option 2',
					 ),
					'multiple' => true,
				),
				array(
					'id' => 'tf-color',
					'type' => 'color',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'default' => '#ffffff',
					'multiple' => true,
					'inline' => true,
					'colors' => array(
						'title' => 'Title',
						'subtitle' => 'Subtitle',
						'content' => 'Content',
					 ),
				),
				array(
					'id' => 'tf-icon',
					'type' => 'icon',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
					'default' => 'fa fa-home',
				),
				array(
					'id' => 'tf-image',
					'type' => 'image',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
				),
				array(
					'id' => 'tf-gallery',
					'type' => 'gallery',
					'label' => 'Enter your label',
					'subtitle' => 'Enter your subtitle',
					'description' => 'Enter your description',
					'class' => 'tf-field-class',
				),

				
			),
		),
		'section_3' => array(
			'title'  => 'Section 1',
			'icon'   => 'fa-solid fa-user-pen',
			'fields' => array(
				array(
					'id'          => 'zip',
					'title'       => 'Zip',
					'type'        => 'text',
					'placeholder' => 'Zip of the hotel',
					'description' => 'Zip of the hotel',
				),
				array(
					'id'          => 'googlemap',
					'label'       => 'Textarea 2',
					'type'        => 'map',
					'description' => 'room details hotel',
				),
				array(
					'id'          => 'googlemap-testing',
					'label'       => 'Textarea 2',
					'type'        => 'map',
					'description' => 'room details hotel',
				),
			),
		),
	),
) );
